project:
  type: website
  output-dir: docs


website:
  title: "Rural MN Migration Trends"
  navbar:
    left:
      - href: index.qmd
        text: Summary
      - text: Data Prep and Summaries
        icon: fa-gear
        menu:
          - text: K12Enrollment
            href: k12enrollment.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true