<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Post-secondary Paths CART – Pathways taken after high school - Northeast</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.33/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">
<script src="site_libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="site_libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">
<script src="site_libs/selectize-0.12.0/selectize.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Pathways taken after high school - Northeast</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-prep-and-summaries" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Data Prep and Summaries</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-prep-and-summaries">    
        <li>
    <a class="dropdown-item" href="./k12enrollment.html">
 <span class="dropdown-text">K12Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./k12orgs.html">
 <span class="dropdown-text">K12Orgs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./act.html">
 <span class="dropdown-text">ACT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ap.html">
 <span class="dropdown-text">AP</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cteenrollment.html">
 <span class="dropdown-text">CTEEnrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ctedemographics.html">
 <span class="dropdown-text">CTEDemographics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assessments.html">
 <span class="dropdown-text">Assessments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sat.html">
 <span class="dropdown-text">SAT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nscenrollment.html">
 <span class="dropdown-text">National Student Clearinghouse - Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nsccompletions.html">
 <span class="dropdown-text">National Student Clearinghouse - Completions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./employment.html">
 <span class="dropdown-text">Employment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./emp_states_each_year.html">
 <span class="dropdown-text">Employment states each year</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unemployment.html">
 <span class="dropdown-text">Unemployment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./avgwages.html">
 <span class="dropdown-text">Average wages</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./categorizing_range_schools.html">
 <span class="dropdown-text">Categorizing Range Schools</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis">    
        <li>
    <a class="dropdown-item" href="./analysis_mca.html">
 <span class="dropdown-text">Multiple Correspondence Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_dep_var_states.html">
 <span class="dropdown-text">Dependent Variable States</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_ct.html">
 <span class="dropdown-text">Local Employment Cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_pathways_ct.html">
 <span class="dropdown-text">Post-secondary pathways cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_CART.html">
 <span class="dropdown-text">Local Employment CART Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_paths_CART.html">
 <span class="dropdown-text">Post-secondary pathways CART</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_non_post_secondary_graduates.html">
 <span class="dropdown-text">Non-college graduates</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_non_college_deeper.html">
 <span class="dropdown-text">Further analysis on non-college grads</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-one-page-summaries-of-pathways" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">One-page summaries of pathways</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-one-page-summaries-of-pathways">    
        <li>
    <a class="dropdown-item" href="./pathway_anchored.html">
 <span class="dropdown-text">Pathway - Anchored</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pathway_mobility.html">
 <span class="dropdown-text">Pathway - Mobility</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pathway_unanchored.html">
 <span class="dropdown-text">Pathway - Unanchared / At-Risk</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#post-secondary-paths" id="toc-post-secondary-paths" class="nav-link active" data-scroll-target="#post-secondary-paths">Post-secondary Paths</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#analysis---post-secondary-location" id="toc-analysis---post-secondary-location" class="nav-link" data-scroll-target="#analysis---post-secondary-location">Analysis - Post secondary location</a>
  <ul class="collapse">
  <li><a href="#base-model" id="toc-base-model" class="nav-link" data-scroll-target="#base-model">Base Model</a></li>
  <li><a href="#pre-pruning" id="toc-pre-pruning" class="nav-link" data-scroll-target="#pre-pruning">Pre-pruning</a></li>
  <li><a href="#post-pruning" id="toc-post-pruning" class="nav-link" data-scroll-target="#post-pruning">Post-pruning</a></li>
  <li><a href="#main-takeaway" id="toc-main-takeaway" class="nav-link" data-scroll-target="#main-takeaway"><strong>Main takeaway</strong></a></li>
  </ul></li>
  <li><a href="#analysis---highest-credential-earned" id="toc-analysis---highest-credential-earned" class="nav-link" data-scroll-target="#analysis---highest-credential-earned">Analysis - Highest Credential Earned</a>
  <ul class="collapse">
  <li><a href="#base-model-1" id="toc-base-model-1" class="nav-link" data-scroll-target="#base-model-1">Base Model</a></li>
  <li><a href="#pre-pruning-1" id="toc-pre-pruning-1" class="nav-link" data-scroll-target="#pre-pruning-1">Pre-pruning</a></li>
  <li><a href="#post-pruning-1" id="toc-post-pruning-1" class="nav-link" data-scroll-target="#post-pruning-1">Post-pruning</a></li>
  <li><a href="#main-takeaway-1" id="toc-main-takeaway-1" class="nav-link" data-scroll-target="#main-takeaway-1"><strong>Main takeaway</strong></a></li>
  </ul></li>
  <li><a href="#comparison" id="toc-comparison" class="nav-link" data-scroll-target="#comparison">Comparison</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Post-secondary Paths CART</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>master.original <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/SLEDS/Masters/After analysis/Master-after-ct.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"1"</span>, <span class="st">"Public, 4-year"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"4"</span>, <span class="st">"Public, 2-year"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"11"</span>, <span class="st">"Other"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.location =</span> <span class="fu">ifelse</span>(ps.grad.location <span class="sc">==</span> <span class="st">"PS grad EDR"</span>, <span class="st">"PS grad region"</span>, ps.grad.location),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level =</span> <span class="fu">as.factor</span>(highest.cred.level),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.location =</span> <span class="fu">as.factor</span>(ps.grad.location))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(master.original))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PersonID</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="even">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">took.ACT</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="even">
<td style="text-align: left;">attended.ps</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps.first.year</td>
</tr>
<tr class="even">
<td style="text-align: left;">attended.ps.years.hsgrad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps.within.first.year.hsgrad</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.ruca</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.pr</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.MN</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTE.SPED</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Agriculture..Food..and.Natural.Resources</td>
</tr>
<tr class="even">
<td style="text-align: left;">Architecture…Construction</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arts..A.V.Technology…Communication</td>
</tr>
<tr class="even">
<td style="text-align: left;">Business..Management…Administrative</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diversified</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education…Training</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Finance</td>
</tr>
<tr class="even">
<td style="text-align: left;">Government…Public.Administration</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Health.Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hospitality…Tourism</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Human.Services</td>
</tr>
<tr class="even">
<td style="text-align: left;">Information.Technology</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Law..Public.Safety…Security</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufacturing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marketing</td>
</tr>
<tr class="even">
<td style="text-align: left;">Program.Area..Diversified.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Science..Technology..Engineering….Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transportation..Distribution…Logistics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Handicapped</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Handicapped..16.20..on.IEP.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Career.Exploration..age.14.15.on.I</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Disadvantaged</td>
</tr>
<tr class="even">
<td style="text-align: left;">Youth.Apprenticeship</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="even">
<td style="text-align: left;">n.institutions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">wages.3year.avg</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.10</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(master.original))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">PersonID</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: left;">grad.year.covid</th>
<th style="text-align: right;">economic.status</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: left;">took.ACT</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: left;">attended.ps</th>
<th style="text-align: right;">attended.ps.first.year</th>
<th style="text-align: right;">attended.ps.years.hsgrad</th>
<th style="text-align: left;">attended.ps.within.first.year.hsgrad</th>
<th style="text-align: left;">ps.grad</th>
<th style="text-align: left;">ps.grad.InstitutionSector</th>
<th style="text-align: left;">highest.cred.level</th>
<th style="text-align: left;">ps.grad.location</th>
<th style="text-align: left;">ps.grad.in.same.ruca</th>
<th style="text-align: left;">ps.grad.in.same.edr</th>
<th style="text-align: left;">ps.grad.in.same.pr</th>
<th style="text-align: left;">ps.grad.in.MN</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">ACTE.SPED</th>
<th style="text-align: right;">Agriculture..Food..and.Natural.Resources</th>
<th style="text-align: right;">Architecture…Construction</th>
<th style="text-align: right;">Arts..A.V.Technology…Communication</th>
<th style="text-align: right;">Business..Management…Administrative</th>
<th style="text-align: right;">Diversified</th>
<th style="text-align: right;">Education…Training</th>
<th style="text-align: right;">Finance</th>
<th style="text-align: right;">Government…Public.Administration</th>
<th style="text-align: right;">Health.Science</th>
<th style="text-align: right;">Hospitality…Tourism</th>
<th style="text-align: right;">Human.Services</th>
<th style="text-align: right;">Information.Technology</th>
<th style="text-align: right;">Law..Public.Safety…Security</th>
<th style="text-align: right;">Manufacturing</th>
<th style="text-align: right;">Marketing</th>
<th style="text-align: right;">Program.Area..Diversified.</th>
<th style="text-align: right;">Science..Technology..Engineering….Mathematics</th>
<th style="text-align: right;">STEM</th>
<th style="text-align: right;">Transportation..Distribution…Logistics</th>
<th style="text-align: right;">Work.Experience.Handicapped</th>
<th style="text-align: right;">Work.Experience.Handicapped..16.20..on.IEP.</th>
<th style="text-align: right;">Work.Experience.Career.Exploration..age.14.15.on.I</th>
<th style="text-align: right;">Work.Experience.Disadvantaged</th>
<th style="text-align: right;">Youth.Apprenticeship</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: right;">n.institutions</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">wages.3year.avg</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: left;">grad.year.1</th>
<th style="text-align: left;">grad.year.5</th>
<th style="text-align: left;">grad.year.10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6140596</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.166667</td>
<td style="text-align: right;">42711.00</td>
<td style="text-align: right;">0.8152977</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="even">
<td style="text-align: right;">1986818</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.833333</td>
<td style="text-align: right;">54459.33</td>
<td style="text-align: right;">0.8222718</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11614284</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.900000</td>
<td style="text-align: right;">53270.67</td>
<td style="text-align: right;">0.7612995</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="even">
<td style="text-align: right;">8332752</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2016</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Public, 4-year</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad MN</td>
<td style="text-align: left;">Outside RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.366667</td>
<td style="text-align: right;">42007.00</td>
<td style="text-align: right;">0.8253281</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6569729</td>
<td style="text-align: left;">Entirely rural</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2012</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9.366667</td>
<td style="text-align: right;">30618.33</td>
<td style="text-align: right;">0.6800498</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Meaningful emp MN</td>
</tr>
<tr class="even">
<td style="text-align: right;">357415</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Public, 2-year</td>
<td style="text-align: left;">Associate degree</td>
<td style="text-align: left;">PS grad Region</td>
<td style="text-align: left;">In same RUCA</td>
<td style="text-align: left;">In same EDR</td>
<td style="text-align: left;">In same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.566667</td>
<td style="text-align: right;">41980.67</td>
<td style="text-align: right;">0.7499672</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="post-secondary-paths" class="level1">
<h1>Post-secondary Paths</h1>
<p>In the previous analyses, post-secondary variables rose to the top again and again as a primary factor in whether an individual had meaningful employment in the region or not. In particular, these two variables were the highest and broke in the following ways;</p>
<p><u><strong>Postsecondary Graduation Location (<code>ps.grad.location</code>)</strong></u></p>
<p>Graduation location consistently mattered. Those who graduated from a postsecondary institution <strong>within their high school region</strong> had the strongest likelihood of achieving local meaningful employment. Graduates from institutions elsewhere in Minnesota also did relatively well, though not as strongly as regional graduates. Outcomes were weaker for those who graduated from institutions <strong>outside of Minnesota</strong>, and the weakest outcomes were for those who did <strong>not graduate from any postsecondary institution</strong>. This suggests that proximity and local institutional ties play a key role in anchoring graduates in the regional labor market.</p>
<p><u><strong>Highest Credential Earned (`highest.cred.level`)</strong></u></p>
<p>Higher credentials were associated with <strong>greater mobility out of the region</strong>. Bachelor’s and advanced degree holders were less likely to be employed locally compared to those with associate’s degrees or certificates, as higher levels of education often connect individuals to broader labor markets. Conversely, individuals with <strong>certificates or associate’s degrees</strong> had a stronger tendency to remain employed within the region. Those who did not complete a credential had weaker outcomes overall, but among the employed, they were more likely than bachelor’s recipients to stay in local, lower-skill jobs.</p>
<hr>
<p>For both of these variables, we will combine classifications in order to have a smaller set to model against;</p>
<ul>
<li>ps.grad.location
<ol type="1">
<li>PS grad region</li>
<li>PS grad outside region: includes all individuals that graduated from college outside of the region and state.</li>
<li>Did not graduate ps</li>
</ol></li>
<li>highest.cred.level
<ol type="1">
<li>Associate degree or lower</li>
<li>Bachelors or higher</li>
<li>Did not graduate: includes individuals with some college and no college experience.</li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>master <span class="ot">&lt;-</span> master.original <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.location.new =</span> <span class="fu">ifelse</span>(ps.grad.location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"PS grad MN"</span>, <span class="st">"PS grad outside MN"</span>), <span class="st">"PS grad outside region"</span>, <span class="fu">as.character</span>(ps.grad.location)),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level.new =</span> <span class="fu">ifelse</span>(highest.cred.level <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Associate degree"</span>, <span class="st">"Less than Associate Degree"</span>), <span class="st">"Associate degree or lower"</span>, <span class="fu">as.character</span>(highest.cred.level)),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level.new =</span> <span class="fu">ifelse</span>(highest.cred.level.new <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"No college"</span>, <span class="st">"Some college"</span>), <span class="st">"Did not graduate ps"</span>, <span class="fu">as.character</span>(highest.cred.level.new)))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(master))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PersonID</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="even">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">took.ACT</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="even">
<td style="text-align: left;">attended.ps</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps.first.year</td>
</tr>
<tr class="even">
<td style="text-align: left;">attended.ps.years.hsgrad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps.within.first.year.hsgrad</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.ruca</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.pr</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.MN</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTE.SPED</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Agriculture..Food..and.Natural.Resources</td>
</tr>
<tr class="even">
<td style="text-align: left;">Architecture…Construction</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arts..A.V.Technology…Communication</td>
</tr>
<tr class="even">
<td style="text-align: left;">Business..Management…Administrative</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diversified</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education…Training</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Finance</td>
</tr>
<tr class="even">
<td style="text-align: left;">Government…Public.Administration</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Health.Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hospitality…Tourism</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Human.Services</td>
</tr>
<tr class="even">
<td style="text-align: left;">Information.Technology</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Law..Public.Safety…Security</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufacturing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marketing</td>
</tr>
<tr class="even">
<td style="text-align: left;">Program.Area..Diversified.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Science..Technology..Engineering….Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transportation..Distribution…Logistics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Handicapped</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Handicapped..16.20..on.IEP.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Career.Exploration..age.14.15.on.I</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Disadvantaged</td>
</tr>
<tr class="even">
<td style="text-align: left;">Youth.Apprenticeship</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="even">
<td style="text-align: left;">n.institutions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">wages.3year.avg</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location.new</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level.new</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(master))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">PersonID</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: left;">grad.year.covid</th>
<th style="text-align: right;">economic.status</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: left;">took.ACT</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: left;">attended.ps</th>
<th style="text-align: right;">attended.ps.first.year</th>
<th style="text-align: right;">attended.ps.years.hsgrad</th>
<th style="text-align: left;">attended.ps.within.first.year.hsgrad</th>
<th style="text-align: left;">ps.grad</th>
<th style="text-align: left;">ps.grad.InstitutionSector</th>
<th style="text-align: left;">highest.cred.level</th>
<th style="text-align: left;">ps.grad.location</th>
<th style="text-align: left;">ps.grad.in.same.ruca</th>
<th style="text-align: left;">ps.grad.in.same.edr</th>
<th style="text-align: left;">ps.grad.in.same.pr</th>
<th style="text-align: left;">ps.grad.in.MN</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">ACTE.SPED</th>
<th style="text-align: right;">Agriculture..Food..and.Natural.Resources</th>
<th style="text-align: right;">Architecture…Construction</th>
<th style="text-align: right;">Arts..A.V.Technology…Communication</th>
<th style="text-align: right;">Business..Management…Administrative</th>
<th style="text-align: right;">Diversified</th>
<th style="text-align: right;">Education…Training</th>
<th style="text-align: right;">Finance</th>
<th style="text-align: right;">Government…Public.Administration</th>
<th style="text-align: right;">Health.Science</th>
<th style="text-align: right;">Hospitality…Tourism</th>
<th style="text-align: right;">Human.Services</th>
<th style="text-align: right;">Information.Technology</th>
<th style="text-align: right;">Law..Public.Safety…Security</th>
<th style="text-align: right;">Manufacturing</th>
<th style="text-align: right;">Marketing</th>
<th style="text-align: right;">Program.Area..Diversified.</th>
<th style="text-align: right;">Science..Technology..Engineering….Mathematics</th>
<th style="text-align: right;">STEM</th>
<th style="text-align: right;">Transportation..Distribution…Logistics</th>
<th style="text-align: right;">Work.Experience.Handicapped</th>
<th style="text-align: right;">Work.Experience.Handicapped..16.20..on.IEP.</th>
<th style="text-align: right;">Work.Experience.Career.Exploration..age.14.15.on.I</th>
<th style="text-align: right;">Work.Experience.Disadvantaged</th>
<th style="text-align: right;">Youth.Apprenticeship</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: right;">n.institutions</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">wages.3year.avg</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: left;">grad.year.1</th>
<th style="text-align: left;">grad.year.5</th>
<th style="text-align: left;">grad.year.10</th>
<th style="text-align: left;">ps.grad.location.new</th>
<th style="text-align: left;">highest.cred.level.new</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6140596</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.166667</td>
<td style="text-align: right;">42711.00</td>
<td style="text-align: right;">0.8152977</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">1986818</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.833333</td>
<td style="text-align: right;">54459.33</td>
<td style="text-align: right;">0.8222718</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11614284</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.900000</td>
<td style="text-align: right;">53270.67</td>
<td style="text-align: right;">0.7612995</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">8332752</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2016</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Public, 4-year</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad MN</td>
<td style="text-align: left;">Outside RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.366667</td>
<td style="text-align: right;">42007.00</td>
<td style="text-align: right;">0.8253281</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">PS grad outside region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6569729</td>
<td style="text-align: left;">Entirely rural</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2012</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9.366667</td>
<td style="text-align: right;">30618.33</td>
<td style="text-align: right;">0.6800498</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">357415</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Public, 2-year</td>
<td style="text-align: left;">Associate degree</td>
<td style="text-align: left;">PS grad Region</td>
<td style="text-align: left;">In same RUCA</td>
<td style="text-align: left;">In same EDR</td>
<td style="text-align: left;">In same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.566667</td>
<td style="text-align: right;">41980.67</td>
<td style="text-align: right;">0.7499672</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">PS grad Region</td>
<td style="text-align: left;">Associate degree or lower</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>This study investigates the factors that influence what secondary education pathway a high school graduate follows. To isolate and understand the predictors of this specific outcome, the analysis compares it separately against three alternative post-secondary variables:</p>
<ol type="1">
<li>Post-secondary graduation location</li>
<li>Highest Credential Earned in Post-secondary</li>
</ol>
<p>Graduates classified as <em>Attending post-secondary</em> for either of these are excluded from the analysis.</p>
<p>The modeling process follows these steps:</p>
<ol type="1">
<li><p><strong>Data Preparation</strong> All predictor variables include demographic characteristics, high school characteristics, and high school achievement indicators. Records with missing target outcome categories are excluded.</p></li>
<li><p><strong>Training and Test Split</strong> For each post-secondary variable, the data is randomly split into a training set (70–80%) and a testing set (20–30%) to ensure that model evaluation is conducted on previously unseen data.</p></li>
<li><p><strong>Modeling</strong></p>
<p>We are going to use the following method to each comparison:</p>
<ul>
<li><strong>CART (Classification and Regression Tree)</strong> for interpretability and identification of clear decision rules. We will start by developing the base model, and then do pre- and post-pruning to determine which model provides the best accuracy.</li>
</ul></li>
<li><p><strong>Evaluation</strong> Models are evaluated on the testing set using accuracy, Cohen’s kappa, balanced accuracy, sensitivity, and specificity. Variable importance is examined to identify the most influential predictors for each comparison and time point.</p></li>
</ol>
<p>This approach emphasizes clarity in interpretation by focusing each mode three post-secondary distinctions, making it easier to identify which factors most strongly differentiate graduates who follow pathways that lead to secondary pathways that benefit regional workforce employment.</p>
<p><br></p>
</section>
<section id="analysis---post-secondary-location" class="level1">
<h1>Analysis - Post secondary location</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> master <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(economic.status, RaceEthnicity, SpecialEdStatus, Dem_Desc, avg.unemp.rate, avg.wages.pct.state, ACTCompositeScore, took.ACT, pseo.participant, cte.achievement, total.cte.courses.taken, MCA.M, MCA.R, MCA.S, ps.grad.location.new, highest.cred.level.new)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="even">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="even">
<td style="text-align: left;">took.ACT</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location.new</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level.new</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">economic.status</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: left;">took.ACT</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: left;">ps.grad.location.new</th>
<th style="text-align: left;">highest.cred.level.new</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">5.166667</td>
<td style="text-align: right;">0.8152977</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">4.833333</td>
<td style="text-align: right;">0.8222718</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: right;">4.900000</td>
<td style="text-align: right;">0.7612995</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">5.366667</td>
<td style="text-align: right;">0.8253281</td>
<td style="text-align: right;">26</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">PS grad outside region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Entirely rural</td>
<td style="text-align: right;">9.366667</td>
<td style="text-align: right;">0.6800498</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">4.566667</td>
<td style="text-align: right;">0.7499672</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">PS grad Region</td>
<td style="text-align: left;">Associate degree or lower</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table below shows that 58% of the individuals did not graduate college, 18% graduated outside their high school region, and 25% graduated from a college within their region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ps.grad.location <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>highest.cred.level.new) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ps.grad.location.new <span class="sc">!=</span> <span class="st">"Attending ps"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.location.new =</span> <span class="fu">as.factor</span>(ps.grad.location.new))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">comma</span>(<span class="fu">nrow</span>(ps.grad.location))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "44,035"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(<span class="at">data =</span> ps.grad.location <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(ps.grad.location.new) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">pct =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">class =</span> <span class="st">"cell-border stripe"</span>, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">filter =</span> <span class="st">"top"</span>, </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">options =</span> <span class="fu">list</span>(</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">columnDefs =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">className =</span> <span class="st">"dt-center"</span>, <span class="at">targets =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatCurrency</span>(<span class="dv">2</span>, <span class="st">""</span>, <span class="at">digits =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatPercentage</span>(<span class="dv">3</span>, <span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-cf55662d1804139fd9b0" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-cf55662d1804139fd9b0">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;Did not graduate ps&quot;,&quot;PS grad outside region&quot;,&quot;PS grad Region&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"7730\" data-max=\"25390\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.175542182354944\" data-max=\"0.576586805949813\" data-scale=\"15\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["Did not graduate ps","PS grad outside region","PS grad Region"],[25390,7730,10915],[0.5765868059498126,0.1755421823549449,0.2478710116952424]],"container":"<table class=\"cell-border stripe\">\n  <thead>\n    <tr>\n      <th>ps.grad.location.new<\/th>\n      <th>n<\/th>\n      <th>pct<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \",\", \".\", null);\n  }"},{"targets":1,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \"\", 0, 3, \",\", \".\", true, null);\n  }"},{"className":"dt-center","targets":[1,2]},{"name":"ps.grad.location.new","targets":0},{"name":"n","targets":1},{"name":"pct","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render"],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<section id="base-model" class="level2">
<h2 class="anchored" data-anchor-id="base-model">Base Model</h2>
<p>I know the base model is going to overfit and provide an overly complex tree due to having a cost penalty of 0. So I’m just going to print the complexity plot in order to see what the appropriate CP would be to minimize xerror.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(ps.grad.location), <span class="fu">nrow</span>(ps.grad.location) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> ps.grad.location[sample_ind,]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> ps.grad.location[<span class="sc">-</span>sample_ind,]</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Base model</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(ps.grad.location.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>))</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>accuracy_base <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_base, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "59.2%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
 [1] ACTCompositeScore       avg.unemp.rate          avg.wages.pct.state    
 [4] cte.achievement         Dem_Desc                economic.status        
 [7] MCA.M                   MCA.R                   MCA.S                  
[10] pseo.participant        RaceEthnicity           SpecialEdStatus        
[13] took.ACT                total.cte.courses.taken

Root node error: 13092/30824 = 0.42473

n= 30824 

           CP nsplit rel error  xerror      xstd
1  2.0108e-02      0   1.00000 1.00000 0.0066287
2  1.8637e-02      4   0.91957 0.91583 0.0065378
3  1.1075e-02      5   0.90093 0.89994 0.0065165
4  1.8332e-03      6   0.88986 0.89459 0.0065091
5  1.2985e-03      8   0.88619 0.89207 0.0065055
6  1.0885e-03     11   0.88199 0.89360 0.0065077
7  1.0694e-03     15   0.87764 0.89459 0.0065091
8  8.7840e-04     16   0.87657 0.89299 0.0065068
9  8.1475e-04     21   0.87214 0.89123 0.0065043
10 8.0202e-04     24   0.86969 0.89108 0.0065041
11 6.8744e-04     26   0.86809 0.89207 0.0065055
12 5.3468e-04     28   0.86671 0.89177 0.0065051
13 4.9649e-04     29   0.86618 0.89062 0.0065034
14 4.8376e-04     33   0.86389 0.89138 0.0065045
15 4.5830e-04     36   0.86244 0.89192 0.0065053
16 4.2010e-04     39   0.86106 0.89161 0.0065048
17 4.1247e-04     44   0.85869 0.89154 0.0065047
18 4.0737e-04     49   0.85663 0.89154 0.0065047
19 3.9464e-04     52   0.85541 0.89154 0.0065047
20 3.8191e-04     61   0.85144 0.89093 0.0065039
21 3.5645e-04     68   0.84876 0.89031 0.0065030
22 3.4372e-04     71   0.84769 0.89291 0.0065067
23 3.3099e-04     84   0.84135 0.89536 0.0065101
24 3.0553e-04    109   0.83188 0.89536 0.0065101
25 2.8007e-04    119   0.82883 0.89490 0.0065095
26 2.7498e-04    126   0.82684 0.89383 0.0065080
27 2.6734e-04    134   0.82432 0.89505 0.0065097
28 2.5461e-04    137   0.82340 0.89490 0.0065095
29 2.4824e-04    140   0.82264 0.89581 0.0065108
30 2.4442e-04    151   0.81981 0.89581 0.0065108
31 2.2915e-04    164   0.81638 0.89543 0.0065102
32 2.1642e-04    213   0.80469 0.89474 0.0065093
33 2.1005e-04    227   0.80125 0.89406 0.0065083
34 2.0369e-04    232   0.80011 0.89543 0.0065102
35 1.9096e-04    241   0.79827 0.89536 0.0065101
36 1.7823e-04    277   0.78987 0.89650 0.0065117
37 1.7186e-04    283   0.78880 0.89650 0.0065117
38 1.5277e-04    298   0.78537 0.90200 0.0065193
39 1.3367e-04    427   0.76428 0.90590 0.0065246
40 1.3094e-04    440   0.76245 0.90956 0.0065296
41 1.2730e-04    447   0.76153 0.90995 0.0065301
42 1.2221e-04    477   0.75687 0.91468 0.0065363
43 1.1457e-04    494   0.75474 0.91674 0.0065390
44 1.0503e-04    567   0.74572 0.92148 0.0065450
45 1.0184e-04    593   0.74206 0.92346 0.0065475
46 9.5478e-05    638   0.73709 0.92606 0.0065508
47 8.9113e-05    642   0.73671 0.92606 0.0065508
48 8.7294e-05    648   0.73617 0.92606 0.0065508
49 7.6383e-05    655   0.73556 0.93989 0.0065675
50 6.9439e-05    785   0.72540 0.94126 0.0065691
51 6.8342e-05    798   0.72434 0.94302 0.0065711
52 6.6835e-05    951   0.70646 0.94577 0.0065743
53 6.3652e-05    959   0.70593 0.94607 0.0065746
54 6.1106e-05    966   0.70547 0.94814 0.0065770
55 5.7287e-05    976   0.70486 0.94859 0.0065775
56 5.0922e-05    985   0.70432 0.95325 0.0065827
57 4.5830e-05   1012   0.70295 0.95455 0.0065841
58 4.2435e-05   1036   0.70173 0.95547 0.0065851
59 3.8191e-05   1047   0.70119 0.95975 0.0065898
60 3.0553e-05   1123   0.69829 0.96089 0.0065910
61 2.5461e-05   1156   0.69722 0.96677 0.0065972
62 2.1824e-05   1180   0.69661 0.96761 0.0065980
63 2.0832e-05   1187   0.69646 0.96761 0.0065980
64 1.9096e-05   1198   0.69623 0.96845 0.0065989
65 1.6974e-05   1214   0.69592 0.96868 0.0065991
66 1.5277e-05   1223   0.69577 0.96922 0.0065997
67 1.2730e-05   1248   0.69539 0.96998 0.0066004
68 9.5478e-06   1254   0.69531 0.96998 0.0066004
69 0.0000e+00   1262   0.69523 0.97029 0.0066008</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 59.2%</li>
<li><strong>Variables used:</strong> 14
<ul>
<li>Demographics: 3/3</li>
<li>High school characteristics: 3/3</li>
<li>High school accomplishments: 8/8</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong> Step 21, xerror = .89025, cp = 3.5645e-04, splits = 68</li>
<li><strong>Total splits:</strong> 1,262</li>
</ul>
<p><br></p>
</section>
<section id="pre-pruning" class="level2">
<h2 class="anchored" data-anchor-id="pre-pruning">Pre-pruning</h2>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket. It’s recommended that I start with the following parameters;</p>
<ul>
<li>maxdepth: 5</li>
<li>minsplit: round(2% of nrow(train)) which is 616.</li>
<li>minbucket: round(minsplit / 3) which is 205</li>
<li>cp = 0</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>maxdepth <span class="ot">=</span> <span class="dv">6</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>minsplit <span class="ot">=</span> <span class="fu">round</span>(.<span class="dv">02</span><span class="sc">*</span><span class="fu">nrow</span>(train))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>minbucket <span class="ot">=</span> <span class="fu">round</span>(minsplit <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(ps.grad.location.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> maxdepth, <span class="at">minsplit =</span> minsplit, <span class="at">minbucket =</span> minbucket))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_preprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "62.2%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore economic.status   pseo.participant  RaceEthnicity    
[5] took.ACT         

Root node error: 13092/30824 = 0.42473

n= 30824 

         CP nsplit rel error  xerror      xstd
1 0.0201077      0   1.00000 1.00000 0.0066287
2 0.0186373      4   0.91957 0.91758 0.0065401
3 0.0110755      5   0.90093 0.90086 0.0065178
4 0.0008784      6   0.88986 0.90032 0.0065170
5 0.0000000     10   0.88634 0.90353 0.0065214</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Takeaways</strong></p>
<ul>
<li><strong>Accuracy</strong>: 59.2% -&gt; 62.2%</li>
<li><strong>Variables used:</strong> 5
<ul>
<li>Demographics: 2/3 - race and economic status</li>
<li>High school characteristics: 0/3</li>
<li>High school accomplishments: 3/8 - college prep</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong> Step 4, xerror = .90032, cp = 0.0008784, splits = 6</li>
<li><strong>Total splits:</strong> 10</li>
</ul>
<p><br></p>
</section>
<section id="post-pruning" class="level2">
<h2 class="anchored" data-anchor-id="post-pruning">Post-pruning</h2>
<p>The idea here is to allow the decision tree to grow fully and observe the CP value. There are two methods for identifying the CP code;</p>
<ol type="1">
<li>Use the cp value with the lowest xerror from the base model.</li>
<li>Use the cp value with the next lowest xerror that is within the standard error.</li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> ps.grad.location.model.preprune<span class="sc">$</span>cptable</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>optimal_cp <span class="ot">&lt;-</span> ps.grad.location.model.preprune<span class="sc">$</span>cptable[<span class="fu">which.min</span>(ps.grad.location.model.preprune<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model.postprune <span class="ot">&lt;-</span> rpart<span class="sc">::</span><span class="fu">prune</span>(ps.grad.location.model.preprune, <span class="at">cp =</span> cp_1se)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_postprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "61.5%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore economic.status   RaceEthnicity     took.ACT         

Root node error: 13092/30824 = 0.42473

n= 30824 

        CP nsplit rel error  xerror      xstd
1 0.020108      0   1.00000 1.00000 0.0066287
2 0.018637      4   0.91957 0.91758 0.0065401
3 0.011075      5   0.90093 0.90086 0.0065178</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Takeaways</strong></p>
<ul>
<li><strong>Accuracy</strong>: 62.2% -&gt; 61.5%</li>
<li><strong>Variables used:</strong> 4
<ul>
<li>Demographics: 2/3 - race and economic status</li>
<li>High school characteristics: 0/3</li>
<li>High school accomplishments: 2/8 - college prep</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong> Step 3, xerror = .90086, cp = 0.011075, splits = 5</li>
<li><strong>Total splits:</strong> 5</li>
</ul>
<p>So, the accuracy of these are clear;</p>
<ul>
<li>Base model: 59.2%</li>
<li>Pre-pruned model: 62.2%</li>
<li>Post-pruned model: 61.5%</li>
</ul>
<p>The post-pruned model provides a much simpler model - 5 splits instead of pre-pruned’s 10 splits - while also giving about the same accuracy. I will dive into that one below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(ps.grad.location.model.postprune, <span class="at">nn =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="main-takeaway" class="level2">
<h2 class="anchored" data-anchor-id="main-takeaway"><strong>Main takeaway</strong></h2>
<p><strong>Model Performance</strong><br>
The post-pruned tree achieved <strong>61.5% accuracy</strong> with a root node error of 42.5%. While not extremely high, this accuracy reflects a meaningful improvement over baseline and demonstrates that a small set of predictors can capture important patterns in postsecondary graduation location.</p>
<p><strong>Key Predictors</strong><br>
The most influential predictors retained after pruning were:</p>
<ul>
<li><strong>ACT Composite Score</strong></li>
<li><strong>Economic Status</strong></li>
<li><strong>Race/Ethnicity</strong></li>
<li><strong>Took ACT</strong></li>
</ul>
<p><strong>Interpretation of Tree Structure</strong><br>
Graduation from a <strong>regional postsecondary institution</strong> was most strongly linked with <strong>higher ACT scores (≥28)</strong>. Students demonstrating strong academic preparation were more likely to complete a credential in their home region. This pattern was especially pronounced among those from <strong>economically disadvantaged backgrounds</strong>, suggesting that high-achieving, low-income students often pursued regional options rather than leaving the area.</p>
<p>By contrast, students with <strong>low ACT scores (&lt;20)</strong> or who did not take the ACT were much more likely to not graduate at all. Students with mid-range ACT performance and less clear demographic ties (e.g., race/ethnicity unknown) were more likely to graduate outside the region.</p>
<p><strong>Summary</strong><br>
The CART model indicates that <strong>high academic readiness is the strongest pathway into regional postsecondary graduation</strong>, particularly when paired with economic disadvantage. In other words, the students most anchored to regional institutions were those who combined strong academic performance with fewer economic resources. This suggests that regional colleges play an especially important role in providing access and opportunity for capable but economically constrained students, while lower academic readiness often foreclosed postsecondary completion altogether.</p>
<p><br></p>
</section>
</section>
<section id="analysis---highest-credential-earned" class="level1">
<h1>Analysis - Highest Credential Earned</h1>
<p>The table below shows that 58% of the individuals did not graduate college, 24% graduated with a Bachelor degree or higher, and 18% graduated with an Associate degree or lower.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>highest.cred.level <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ps.grad.location.new) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(highest.cred.level.new <span class="sc">!=</span> <span class="st">"Attending ps"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">highest.cred.level.new =</span> <span class="fu">as.factor</span>(highest.cred.level.new))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">comma</span>(<span class="fu">nrow</span>(highest.cred.level))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "44,036"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(<span class="at">data =</span> highest.cred.level <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(highest.cred.level.new) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">pct =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">class =</span> <span class="st">"cell-border stripe"</span>, </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">filter =</span> <span class="st">"top"</span>, </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">options =</span> <span class="fu">list</span>(</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">columnDefs =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">className =</span> <span class="st">"dt-center"</span>, <span class="at">targets =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatCurrency</span>(<span class="dv">2</span>, <span class="st">""</span>, <span class="at">digits =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatPercentage</span>(<span class="dv">3</span>, <span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-42b49d8285a415ab757b" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-42b49d8285a415ab757b">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;Associate degree or lower&quot;,&quot;Bachelor degree or higher&quot;,&quot;Did not graduate ps&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"7900\" data-max=\"25390\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.179398673812335\" data-max=\"0.576573712417114\" data-scale=\"15\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["Associate degree or lower","Bachelor degree or higher","Did not graduate ps"],[7900,10746,25390],[0.1793986738123354,0.2440276137705514,0.5765737124171133]],"container":"<table class=\"cell-border stripe\">\n  <thead>\n    <tr>\n      <th>highest.cred.level.new<\/th>\n      <th>n<\/th>\n      <th>pct<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \",\", \".\", null);\n  }"},{"targets":1,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \"\", 0, 3, \",\", \".\", true, null);\n  }"},{"className":"dt-center","targets":[1,2]},{"name":"highest.cred.level.new","targets":0},{"name":"n","targets":1},{"name":"pct","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render"],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<section id="base-model-1" class="level2">
<h2 class="anchored" data-anchor-id="base-model-1">Base Model</h2>
<p>I know the base model is going to overfit and provide an overly complex tree due to having a cost penalty of 0. So I’m just going to print the complexity plot in order to see what the appropriate CP would be to minimize xerror.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(highest.cred.level), <span class="fu">nrow</span>(highest.cred.level) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> highest.cred.level[sample_ind,]</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> highest.cred.level[<span class="sc">-</span>sample_ind,]</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Base model</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(highest.cred.level.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>))</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>accuracy_base <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_base, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "62.4%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
 [1] ACTCompositeScore       avg.unemp.rate          avg.wages.pct.state    
 [4] cte.achievement         Dem_Desc                economic.status        
 [7] MCA.M                   MCA.R                   MCA.S                  
[10] pseo.participant        RaceEthnicity           SpecialEdStatus        
[13] took.ACT                total.cte.courses.taken

Root node error: 13101/30825 = 0.42501

n= 30825 

           CP nsplit rel error  xerror      xstd
1  8.7703e-02      0   1.00000 1.00000 0.0066249
2  2.1830e-02      2   0.82459 0.82459 0.0063940
3  5.5339e-03      3   0.80276 0.80276 0.0063537
4  1.4503e-03      5   0.79170 0.79292 0.0063346
5  1.3739e-03      6   0.79025 0.78910 0.0063271
6  1.3231e-03     12   0.77979 0.78620 0.0063213
7  9.9229e-04     15   0.77582 0.78391 0.0063167
8  8.3963e-04     18   0.77284 0.78162 0.0063120
9  7.6330e-04     20   0.77116 0.78208 0.0063130
10 7.2514e-04     21   0.77040 0.78269 0.0063142
11 6.1064e-04     25   0.76704 0.78193 0.0063127
12 5.3431e-04     26   0.76643 0.78040 0.0063096
13 4.1982e-04     27   0.76590 0.78109 0.0063110
14 4.0709e-04     30   0.76437 0.78101 0.0063108
15 3.8165e-04     36   0.76193 0.78147 0.0063117
16 3.4349e-04     38   0.76116 0.78215 0.0063131
17 3.0532e-04     44   0.75910 0.78360 0.0063161
18 2.9578e-04     62   0.75345 0.78353 0.0063159
19 2.7988e-04     74   0.74948 0.78490 0.0063187
20 2.6716e-04     86   0.74544 0.78605 0.0063210
21 2.2899e-04     98   0.74200 0.78734 0.0063236
22 2.0355e-04    124   0.73552 0.79032 0.0063295
23 1.9083e-04    136   0.73292 0.79269 0.0063341
24 1.7810e-04    149   0.73040 0.79383 0.0063364
25 1.6962e-04    155   0.72933 0.79399 0.0063367
26 1.6538e-04    179   0.72506 0.79902 0.0063465
27 1.5266e-04    192   0.72254 0.79948 0.0063474
28 1.4418e-04    309   0.70231 0.80414 0.0063563
29 1.4176e-04    359   0.69353 0.80551 0.0063589
30 1.3358e-04    368   0.69216 0.80795 0.0063635
31 1.3085e-04    381   0.69002 0.80788 0.0063633
32 1.2722e-04    388   0.68911 0.80818 0.0063639
33 1.2213e-04    400   0.68758 0.81101 0.0063692
34 1.1450e-04    420   0.68499 0.81230 0.0063716
35 1.0904e-04    527   0.67170 0.81956 0.0063849
36 1.0686e-04    534   0.67094 0.82024 0.0063861
37 1.0495e-04    546   0.66949 0.82299 0.0063911
38 1.0177e-04    554   0.66865 0.82391 0.0063927
39 9.5413e-05    578   0.66621 0.82665 0.0063976
40 8.7234e-05    610   0.66277 0.82734 0.0063988
41 7.6330e-05    619   0.66193 0.84055 0.0064217
42 6.1064e-05    772   0.65010 0.84322 0.0064262
43 5.7248e-05    777   0.64980 0.84848 0.0064350
44 5.4521e-05    790   0.64903 0.85406 0.0064442
45 5.3431e-05    812   0.64758 0.85406 0.0064442
46 5.0887e-05    822   0.64705 0.85474 0.0064453
47 4.8574e-05    887   0.64361 0.85635 0.0064479
48 4.5798e-05    902   0.64278 0.85742 0.0064496
49 4.4526e-05    907   0.64255 0.85780 0.0064502
50 3.8165e-05    922   0.64178 0.86680 0.0064644
51 3.4695e-05    990   0.63919 0.86734 0.0064652
52 3.3924e-05   1001   0.63881 0.86848 0.0064670
53 3.0532e-05   1010   0.63850 0.86993 0.0064692
54 2.5443e-05   1020   0.63812 0.87360 0.0064748
55 2.3486e-05   1048   0.63728 0.87375 0.0064751
56 1.9083e-05   1064   0.63690 0.87848 0.0064822
57 1.5266e-05   1128   0.63568 0.87848 0.0064822
58 1.0904e-05   1148   0.63537 0.88123 0.0064863
59 8.4811e-06   1162   0.63522 0.88207 0.0064875
60 0.0000e+00   1180   0.63507 0.88222 0.0064877</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 62.5%</li>
<li><strong>Variables used:</strong> 14
<ul>
<li>Demographics: 3/3</li>
<li>High school characteristics: 3/3</li>
<li>High school accomplishments: 8/8</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong> Step 12, xerror = 0.78040, cp = 5.3431e-04, splits = 26</li>
<li><strong>Total splits:</strong> 1,180</li>
</ul>
<p><br></p>
</section>
<section id="pre-pruning-1" class="level2">
<h2 class="anchored" data-anchor-id="pre-pruning-1">Pre-pruning</h2>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket. It’s recommended that I start with the following parameters;</p>
<ul>
<li>maxdepth: 5</li>
<li>minsplit: round(2% of nrow(train)) which is 616.</li>
<li>minbucket: round(minsplit / 3) which is 205.</li>
<li>cp = 0</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>maxdepth <span class="ot">=</span> <span class="dv">5</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>minsplit <span class="ot">=</span> <span class="fu">round</span>(.<span class="dv">02</span><span class="sc">*</span><span class="fu">nrow</span>(train))</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>minbucket <span class="ot">=</span> <span class="fu">round</span>(minsplit <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(highest.cred.level.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> maxdepth, <span class="at">minsplit =</span> minsplit, <span class="at">minbucket =</span> minbucket))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_preprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "65.9%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore economic.status   RaceEthnicity     took.ACT         

Root node error: 13101/30825 = 0.42501

n= 30825 

         CP nsplit rel error  xerror      xstd
1 0.0877032      0   1.00000 1.00000 0.0066249
2 0.0218304      2   0.82459 0.82459 0.0063940
3 0.0055339      3   0.80276 0.80276 0.0063537
4 0.0000000      5   0.79170 0.79215 0.0063331</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Takeaways</strong></p>
<ul>
<li><strong>Accuracy</strong>: 62.5% -&gt; 65.9%</li>
<li><strong>Variables used:</strong> 4
<ul>
<li>Demographics: 2/3 - Race and economic status</li>
<li>High school characteristics: 0/3</li>
<li>High school accomplishments: 2/8 ACT score</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong> Step 4, xerror = 0.79215, cp = 0, splits = 5</li>
<li><strong>Total splits:</strong> 1,180</li>
</ul>
<p><br></p>
</section>
<section id="post-pruning-1" class="level2">
<h2 class="anchored" data-anchor-id="post-pruning-1">Post-pruning</h2>
<p>The idea here is to allow the decision tree to grow fully and observe the CP value. There are two methods for identifying the CP code;</p>
<ol type="1">
<li>Use the cp value with the lowest xerror from the base model.</li>
<li>Use the cp value with the next lowest xerror that is within the standard error.</li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> highest.cred.level.model.preprune<span class="sc">$</span>cptable</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>optimal_cp <span class="ot">&lt;-</span> highest.cred.level.model.preprune<span class="sc">$</span>cptable[<span class="fu">which.min</span>(highest.cred.level.model.preprune<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model.postprune <span class="ot">&lt;-</span> rpart<span class="sc">::</span><span class="fu">prune</span>(highest.cred.level.model.preprune, <span class="at">cp =</span> cp_1se)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_postprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "65.9%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore economic.status   RaceEthnicity     took.ACT         

Root node error: 13101/30825 = 0.42501

n= 30825 

         CP nsplit rel error  xerror      xstd
1 0.0877032      0   1.00000 1.00000 0.0066249
2 0.0218304      2   0.82459 0.82459 0.0063940
3 0.0055339      3   0.80276 0.80276 0.0063537
4 0.0000000      5   0.79170 0.79215 0.0063331</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Takeaways</strong></p>
<ul>
<li><strong>Accuracy</strong>: 65.9% -&gt; 65.9%</li>
<li><strong>Variables used:</strong> 4
<ul>
<li>Demographics: 2/3 - Race and economic status</li>
<li>High school characteristics: 0/3</li>
<li>High school accomplishments: 2/8 ACT score</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong> Step 4, xerror = 0.79215, cp = 0, splits = 5</li>
<li><strong>Total splits:</strong> 1,180</li>
</ul>
<p>So, the accuracy of these are clear;</p>
<ul>
<li>Base model: 62.4%</li>
<li>Pre-pruned model: 65.9%</li>
<li>Post-pruned model: 65.9%</li>
</ul>
<p>The pre-pruned model is the same as the post-prune model and provides a simple, 5 split tree. I will dive into that one below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(highest.cred.level.model.preprune, <span class="at">nn =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="main-takeaway-1" class="level2">
<h2 class="anchored" data-anchor-id="main-takeaway-1"><strong>Main takeaway</strong></h2>
<p><strong>Model Performance</strong><br>
The pre-pruned CART model achieved an accuracy of <strong>65.9%</strong>, with a root node error of 42.5%. This represents a solid improvement over baseline and indicates that a small set of academic and demographic factors predict credential attainment reasonably well.</p>
<p><strong>Key Predictors</strong><br>
The most influential predictors retained were:</p>
<ul>
<li><strong>ACT Composite Score</strong></li>
<li><strong>Economic Status</strong></li>
<li><strong>Race/Ethnicity</strong></li>
<li><strong>Took ACT</strong></li>
</ul>
<p><strong>Interpretation of Tree Structure</strong><br>
Completion of a <strong>bachelor’s degree or higher</strong> was most strongly linked to taking the ACT and achieving a score of at least 21. Students from across racial/ethnic groups with higher ACT scores, particularly those without economic disadvantage, were the most likely to attain these higher-level credentials.</p>
<p>Students with <strong>low ACT scores (&lt;21)</strong>, or who did not take the ACT at all, were most likely to <strong>not graduate postsecondary</strong>. Economic status compounded this effect, with disadvantaged students at greater risk of non-completion even when they had moderate ACT scores.</p>
<p>Although the tree did not form a distinct pathway that isolated <strong>associate degrees or lower</strong>, these outcomes generally clustered among students with <strong>mid-range ACT scores (21–24)</strong>. Within this range, students with some academic preparation but lower overall scores were less competitive for bachelor’s pathways but still positioned to complete sub-baccalaureate programs. Economic disadvantage increased the likelihood of falling short of a bachelor’s degree, which in many cases meant completing an associate degree or certificate instead of leaving without any credential.</p>
<p><strong>Summary</strong><br>
The CART model highlights three general pathways:</p>
<ol type="1">
<li><strong>Strong ACT performance (≥21), no economic disadvantage → bachelor’s degree or higher</strong></li>
<li><strong>Mid-range ACT performance, especially with disadvantage → associate degree or lower</strong></li>
<li><strong>Low or no ACT performance (&lt;21 or no test) → non-completion</strong></li>
</ol>
<p>In other words, <strong>sub-baccalaureate completion emerges as a “middle pathway,” tied to moderate academic readiness and shaped by socioeconomic constraints</strong>. Students without strong academic signals often fail to complete, while those with higher scores move into bachelor’s attainment. The associate/certificate route, while less cleanly predicted in the tree, reflects a mix of opportunity and constraint: it anchors students with some preparation, but often limited resources, into shorter credentials that still provide local labor market value.</p>
<p><br></p>
</section>
</section>
<section id="comparison" class="level1">
<h1>Comparison</h1>
<p><strong>Comparison of Postsecondary Graduation Location and Highest Credential Earned</strong></p>
<p>Both postsecondary graduation location and highest credential earned emerged as powerful predictors of meaningful employment, but they influenced outcomes in different ways.</p>
<p>Graduation location primarily reflected <strong>where students were most likely to remain employed</strong>. The CART analysis showed that students who graduated from a <strong>regional institution</strong> were the most likely to secure meaningful local employment, demonstrating the strong anchoring effect of nearby colleges. By contrast, students graduating outside the region, especially outside Minnesota, were less likely to stay in the regional labor market. Academic readiness, particularly higher ACT scores, increased the likelihood of completing a regional credential, with disadvantaged students who scored well on the ACT especially anchored to local institutions.</p>
<p>Highest credential earned, on the other hand, shaped <strong>how far students’ employment opportunities extended</strong>. Students who attained a <strong>bachelor’s degree or higher</strong> were less likely to remain employed locally, as these credentials opened access to broader state and national labor markets. In contrast, students with <strong>associate degrees or lower</strong> were more likely to stay in regional employment, reflecting a closer alignment between sub-baccalaureate training and local job structures. Non-completers were at the highest risk of poor employment outcomes altogether, with many remaining in the region but in lower-skill, less stable jobs.</p>
<p><strong>Summary and Policy Implications</strong><br>
Together, the two models highlight a complementary dynamic: <strong>graduation location determines whether students stay rooted in the region, while credential level determines whether they pursue local opportunities or broader labor markets</strong>. Regional institutions play a critical role in anchoring students, particularly those from disadvantaged backgrounds with strong academic preparation, while credential level shapes the degree of geographic mobility.</p>
<p>For policy and planning, this suggests two priorities. First, <strong>strengthening regional postsecondary institutions</strong> can enhance local workforce retention, especially by supporting high-achieving but economically constrained students who might otherwise leave. Second, <strong>expanding opportunities for sub-baccalaureate credentials</strong> can help align education with regional labor market needs, while creating clearer pathways for bachelor’s graduates to find meaningful employment locally may help reduce outmigration. In short, <strong>location ties students to place, while credential level influences the reach of their opportunities</strong>—a balance that policymakers and institutions can shape through program design and workforce partnerships.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>