<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Local Employment CART Analysis – Pathways taken after high school - Northeast</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Pathways taken after high school - Northeast</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-prep-and-summaries" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Data Prep and Summaries</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-prep-and-summaries">    
        <li>
    <a class="dropdown-item" href="./k12enrollment.html">
 <span class="dropdown-text">K12Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./k12orgs.html">
 <span class="dropdown-text">K12Orgs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./act.html">
 <span class="dropdown-text">ACT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ap.html">
 <span class="dropdown-text">AP</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cteenrollment.html">
 <span class="dropdown-text">CTEEnrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ctedemographics.html">
 <span class="dropdown-text">CTEDemographics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assessments.html">
 <span class="dropdown-text">Assessments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sat.html">
 <span class="dropdown-text">SAT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nscenrollment.html">
 <span class="dropdown-text">National Student Clearinghouse - Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nsccompletions.html">
 <span class="dropdown-text">National Student Clearinghouse - Completions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./emp_states_each_year.html">
 <span class="dropdown-text">Employment states each year</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unemployment.html">
 <span class="dropdown-text">Unemployment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./avgwages.html">
 <span class="dropdown-text">Average wages</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis">    
        <li>
    <a class="dropdown-item" href="./analysis_categorizing_range_schools.html">
 <span class="dropdown-text">Categorizing range schools</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_mca.html">
 <span class="dropdown-text">Multiple Correspondence Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_dep_var_states.html">
 <span class="dropdown-text">Dependent Variable States</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_ct.html">
 <span class="dropdown-text">Local Employment Cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_CART.html">
 <span class="dropdown-text">Local Employment CART Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_pathways.html">
 <span class="dropdown-text">Post-secondary pathways</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#methodology" id="toc-methodology" class="nav-link active" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#meaningful-emp-in-ne" id="toc-meaningful-emp-in-ne" class="nav-link" data-scroll-target="#meaningful-emp-in-ne">Meaningful emp in NE</a>
  <ul class="collapse">
  <li><a href="#one-year-after-graduation" id="toc-one-year-after-graduation" class="nav-link" data-scroll-target="#one-year-after-graduation">One year after graduation</a>
  <ul class="collapse">
  <li><a href="#base-model" id="toc-base-model" class="nav-link" data-scroll-target="#base-model">Base model</a></li>
  <li><a href="#pre-pruning" id="toc-pre-pruning" class="nav-link" data-scroll-target="#pre-pruning">Pre-pruning</a></li>
  <li><a href="#post-pruning" id="toc-post-pruning" class="nav-link" data-scroll-target="#post-pruning">Post-pruning</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  <li><a href="#five-years-after-graduation" id="toc-five-years-after-graduation" class="nav-link" data-scroll-target="#five-years-after-graduation">Five years after graduation</a>
  <ul class="collapse">
  <li><a href="#base-model-1" id="toc-base-model-1" class="nav-link" data-scroll-target="#base-model-1">Base model</a></li>
  <li><a href="#pre-pruning-1" id="toc-pre-pruning-1" class="nav-link" data-scroll-target="#pre-pruning-1">Pre-pruning</a></li>
  <li><a href="#post-pruning-1" id="toc-post-pruning-1" class="nav-link" data-scroll-target="#post-pruning-1">Post-pruning</a></li>
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1">Summary</a></li>
  </ul></li>
  <li><a href="#ten-years-after-graduation" id="toc-ten-years-after-graduation" class="nav-link" data-scroll-target="#ten-years-after-graduation">Ten years after graduation</a>
  <ul class="collapse">
  <li><a href="#base-model-2" id="toc-base-model-2" class="nav-link" data-scroll-target="#base-model-2">Base model</a></li>
  <li><a href="#pre-pruning-2" id="toc-pre-pruning-2" class="nav-link" data-scroll-target="#pre-pruning-2">Pre-pruning</a></li>
  <li><a href="#post-pruning-2" id="toc-post-pruning-2" class="nav-link" data-scroll-target="#post-pruning-2">Post-pruning</a></li>
  <li><a href="#summary-2" id="toc-summary-2" class="nav-link" data-scroll-target="#summary-2">Summary</a></li>
  </ul></li>
  <li><a href="#summary-across-time" id="toc-summary-across-time" class="nav-link" data-scroll-target="#summary-across-time">Summary across time</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Local Employment CART Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">PersonID</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: left;">grad.year.covid</th>
<th style="text-align: right;">economic.status</th>
<th style="text-align: left;">range.school</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: left;">took.ACT</th>
<th style="text-align: right;">ap.exam</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: right;">english.learner</th>
<th style="text-align: left;">ps.grad</th>
<th style="text-align: left;">ps.grad.InstitutionSector</th>
<th style="text-align: left;">highest.cred.level</th>
<th style="text-align: left;">ps.grad.location</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: left;">grad.year.1</th>
<th style="text-align: left;">grad.year.5</th>
<th style="text-align: left;">grad.year.10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6140596</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Range school</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="even">
<td style="text-align: right;">1986818</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Non-range school</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11614284</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Non-range school</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="even">
<td style="text-align: right;">8332752</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Non-range school</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">Master degree or higher</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6569729</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Non-range school</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Entirely rural</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Meaningful emp MN</td>
</tr>
<tr class="even">
<td style="text-align: right;">357415</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Non-range school</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">Associate degree</td>
<td style="text-align: left;">In region</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PersonID</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="even">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">range.school</td>
</tr>
<tr class="even">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="even">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="even">
<td style="text-align: left;">took.ACT</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ap.exam</td>
</tr>
<tr class="even">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">english.learner</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="even">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<p>We will use a tree-based method for classification - CART analysis. This type of analysis involves stratifying and/or segmenting the predictor space into a number of simple regions. Essentially, it’s another way to see which independent variables play a role in if an individual has meaningful employment in the local region X. We will be using the independent variables that were identified as being important in the multiple correspondence analysis.</p>
<p>There are a number of states at which we categorize individuals in the dataset;</p>
<ol type="1">
<li>Has meaningful employment in the Northeast region.</li>
<li>Has meaningful employment in Minnesota, but not in Northeast Minnesota.</li>
<li>Is attending post-secondary.</li>
<li>Has a MN employment record but it’s not meaningful, and not attending post-secondary.</li>
<li>Does not have a MN employment record and is not attending post-secondary.</li>
</ol>
<p>There are three “times” in which we checked to see if the individual had meaningful employment within these geographies;</p>
<ol type="1">
<li>one year after graduating high school</li>
<li>five years after graduation, and</li>
<li>ten years after graduation.</li>
</ol>
<p>Meaningful employment is determined by whether an individual worked 1,000 hours for an employer during time X. In addition, if the individual is working for an employer but not meaningful at time X but worked 1,000 hours for that employer during another year it’s still considered “meaningful”.</p>
<p>Due to time x potentially being passed the date of the latest data (2023) for some individuals, the analysis below will filter out all individuals where time x is after 2023.</p>
<p>The primary independent variables that the cross tables indicated as important are;</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>$Gender
[1] "factor"

$grad.year.covid
[1] "factor"

$economic.status
[1] "factor"

$range.school
[1] "factor"

$pseo.participant
[1] "factor"

$SpecialEdStatus
[1] "factor"

$RaceEthnicity
[1] "factor"

$Dem_Desc
[1] "factor"

$took.ACT
[1] "factor"

$ap.exam
[1] "factor"

$cte.achievement
[1] "factor"

$english.learner
[1] "factor"

$ps.grad
[1] "factor"

$ps.grad.InstitutionSector
[1] "factor"

$highest.cred.level
[1] "factor"

$ps.grad.location
[1] "factor"

$ACTCompositeScore
[1] "numeric"

$MCA.M
[1] "numeric"

$MCA.R
[1] "numeric"

$MCA.S
[1] "numeric"

$total.cte.courses.taken
[1] "numeric"</code></pre>
</div>
</div>
<p><br></p>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>We are going to use CART/Decision Trees to see which independent variables are important. One limitation of this method is that the dependent variable must be binary. So, we will need to force our 5 states into 2 states. We will begin by doing the following;</p>
<ol type="1">
<li>Meaningful emp in SW: this will include the following categories for each time.x;</li>
</ol>
<ul>
<li>Meaningful emp in region</li>
</ul>
<ol start="2" type="1">
<li>No meaningful emp in SW: this will include the following categories for each time.x:</li>
</ol>
<ul>
<li>Meaningful emp MN</li>
<li>Attending ps</li>
<li>Not meaningful, not attending ps</li>
<li>No MN emp record, not attending ps</li>
</ul>
<p>Once we look at this analysis, we can determine if we want to split the binary differently for further analysis.</p>
<p><br></p>
</section>
<section id="meaningful-emp-in-ne" class="level1">
<h1>Meaningful emp in NE</h1>
<p>First, let’s re-categorize the dependent variables so that they are binary.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne <span class="ot">&lt;-</span> master <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grad.year.1 =</span> <span class="fu">ifelse</span>(grad.year<span class="fl">.1</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Meaningful emp NE"</span>), <span class="st">"Meaningful emp NE"</span>, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">ifelse</span>(grad.year<span class="fl">.1</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Meaningful emp MN"</span>, <span class="st">"Not meaningful, not attending ps"</span>, <span class="st">"No MN emp record, not attending ps"</span>), <span class="st">"No meaningful emp NE"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="fu">ifelse</span>(grad.year<span class="fl">.1</span> <span class="sc">==</span> <span class="st">"After 2023"</span>, <span class="st">"After 2023"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                                            <span class="fu">ifelse</span>(grad.year<span class="fl">.1</span> <span class="sc">==</span> <span class="st">"Attending ps"</span>, <span class="st">"Attending ps"</span>, <span class="fu">as.character</span>(grad.year<span class="fl">.1</span>))))),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">grad.year.1 =</span> <span class="fu">as.factor</span>(grad.year<span class="fl">.1</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">grad.year.5 =</span> <span class="fu">ifelse</span>(grad.year<span class="fl">.5</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Meaningful emp NE"</span>), <span class="st">"Meaningful emp NE"</span>, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">ifelse</span>(grad.year<span class="fl">.5</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Meaningful emp MN"</span>, <span class="st">"Not meaningful, not attending ps"</span>, <span class="st">"No MN emp record, not attending ps"</span>), <span class="st">"No meaningful emp NE"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                                     <span class="fu">ifelse</span>(grad.year<span class="fl">.5</span> <span class="sc">==</span> <span class="st">"After 2023"</span>, <span class="st">"After 2023"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                                            <span class="fu">ifelse</span>(grad.year<span class="fl">.5</span> <span class="sc">==</span> <span class="st">"Attending ps"</span>, <span class="st">"Attending ps"</span>, <span class="fu">as.character</span>(grad.year<span class="fl">.5</span>))))),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">grad.year.5 =</span> <span class="fu">as.factor</span>(grad.year<span class="fl">.5</span>),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">grad.year.10 =</span> <span class="fu">ifelse</span>(grad.year<span class="fl">.10</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Meaningful emp NE"</span>), <span class="st">"Meaningful emp NE"</span>, </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">ifelse</span>(grad.year<span class="fl">.10</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Meaningful emp MN"</span>, <span class="st">"Not meaningful, not attending ps"</span>, <span class="st">"No MN emp record, not attending ps"</span>), <span class="st">"No meaningful emp NE"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>                                     <span class="fu">ifelse</span>(grad.year<span class="fl">.10</span> <span class="sc">==</span> <span class="st">"After 2023"</span>, <span class="st">"After 2023"</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>                                            <span class="fu">ifelse</span>(grad.year<span class="fl">.10</span> <span class="sc">==</span> <span class="st">"Attending ps"</span>, <span class="st">"Attending ps"</span>, <span class="fu">as.character</span>(grad.year<span class="fl">.10</span>))))),</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">grad.year.10 =</span> <span class="fu">as.factor</span>(grad.year<span class="fl">.10</span>),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">grad.year.1 =</span> <span class="fu">fct_relevel</span>(grad.year<span class="fl">.1</span>, <span class="st">"Meaningful emp NE"</span>, <span class="st">"No meaningful emp NE"</span>, <span class="st">"Attending ps"</span>, <span class="st">"After 2023"</span>),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">grad.year.5 =</span> <span class="fu">fct_relevel</span>(grad.year<span class="fl">.5</span>, <span class="st">"Meaningful emp NE"</span>, <span class="st">"No meaningful emp NE"</span>, <span class="st">"Attending ps"</span>, <span class="st">"After 2023"</span>),</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">grad.year.10 =</span> <span class="fu">fct_relevel</span>(grad.year<span class="fl">.10</span>, <span class="st">"Meaningful emp NE"</span>, <span class="st">"No meaningful emp NE"</span>, <span class="st">"Attending ps"</span>, <span class="st">"After 2023"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<section id="one-year-after-graduation" class="level2">
<h2 class="anchored" data-anchor-id="one-year-after-graduation">One year after graduation</h2>
<p>Since our dependent variable includes a state in which someone is attending post-secondary and the post-secondary variables are related to an individual finishing post-secondary, we will remove “ps.grad.InstitutionSector” and the “highest.cred.level” variable from the analysis.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="even">
<td style="text-align: left;">range.school</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">took.ACT</td>
</tr>
<tr class="even">
<td style="text-align: left;">ap.exam</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="even">
<td style="text-align: left;">english.learner</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="base-model" class="level3">
<h3 class="anchored" data-anchor-id="base-model">Base model</h3>
<p>First we will split the data into two sets, Train and Test, in a 70:30 ratio. The Train set is used for training and creating the model. The Test set is considered to be a dummy production environment to test predictions and evaluate the accuracy of the model.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(meaningful.emp.ne.grad.year<span class="fl">.1</span>), <span class="fu">nrow</span>(meaningful.emp.ne.grad.year<span class="fl">.1</span>) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year<span class="fl">.1</span>[sample_ind,]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year<span class="fl">.1</span>[<span class="sc">-</span>sample_ind,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>Next, we create a decision tree model by calling the rpart function. Let’s first create a base model with default parameters and value. The CP (complexity parameter) is used to control tree growth. If the cost of adding a variable is higher then the value of CP, then tree growth stops.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/decision tree plot meaningful emp NE grad year 1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.1 ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
 [1] ACTCompositeScore         ap.exam                  
 [3] cte.achievement           Dem_Desc                 
 [5] economic.status           Gender                   
 [7] grad.year.covid           highest.cred.level       
 [9] MCA.M                     MCA.R                    
[11] MCA.S                     ps.grad                  
[13] ps.grad.InstitutionSector ps.grad.location         
[15] pseo.participant          RaceEthnicity            
[17] range.school              SpecialEdStatus          
[19] took.ACT                  total.cte.courses.taken  

Root node error: 2901/15927 = 0.18214

n= 15927 

           CP nsplit rel error  xerror     xstd
1  2.6887e-02      0   1.00000 1.00000 0.016791
2  2.2061e-02      1   0.97311 0.99862 0.016782
3  5.1706e-03      2   0.95105 0.95105 0.016463
4  3.1024e-03      3   0.94588 0.95209 0.016471
5  2.4130e-03      4   0.94278 0.95312 0.016478
6  2.0683e-03      7   0.93554 0.95863 0.016515
7  1.8959e-03      9   0.93140 0.95691 0.016503
8  1.7235e-03     11   0.92761 0.95174 0.016468
9  1.6086e-03     14   0.92244 0.94795 0.016442
10 1.3788e-03     17   0.91761 0.94588 0.016428
11 1.2065e-03     18   0.91624 0.94864 0.016447
12 1.1490e-03     23   0.90969 0.94967 0.016454
13 1.0341e-03     30   0.90072 0.94485 0.016421
14 8.6177e-04     34   0.89659 0.94829 0.016445
15 6.8942e-04     39   0.89176 0.95243 0.016473
16 6.0324e-04     43   0.88900 0.95209 0.016471
17 5.1706e-04     48   0.88521 0.95243 0.016473
18 4.8259e-04     53   0.88245 0.95519 0.016492
19 4.5961e-04     59   0.87935 0.95588 0.016496
20 3.4471e-04     65   0.87659 0.95622 0.016499
21 2.5853e-04     69   0.87522 0.96794 0.016578
22 2.2981e-04     81   0.87211 0.98897 0.016718
23 2.0683e-04    141   0.85522 0.98966 0.016723
24 1.9698e-04    151   0.85315 0.99069 0.016730
25 1.7235e-04    158   0.85178 1.00448 0.016820
26 1.4773e-04    172   0.84936 1.01138 0.016864
27 1.1490e-04    179   0.84833 1.01482 0.016887
28 9.4011e-05    188   0.84729 1.02585 0.016957
29 8.6177e-05    199   0.84626 1.03723 0.017029
30 6.8942e-05    207   0.84557 1.03723 0.017029
31 5.7451e-05    212   0.84523 1.05309 0.017128
32 4.9244e-05    230   0.84419 1.05550 0.017143
33 3.8301e-05    237   0.84385 1.05619 0.017147
34 3.4471e-05    246   0.84350 1.05895 0.017165
35 2.6516e-05    256   0.84316 1.05963 0.017169
36 0.0000e+00    269   0.84281 1.05963 0.017169</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/decision tree plot meaningful emp NE grad year 1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>The resulting model produced a VERY complex tree with too many nodes that it isn’t interpretable. However, examining the complexity parameters shows that I have an increasing cross-validated error which provides evidence of a decision tree with too much complexity.</p>
<p>Below are the values in variable importance and there are a couple of themes of importance;</p>
<ol type="1">
<li>post-secondary pathway</li>
<li>cte involvment</li>
<li>Prep for post-secondary</li>
<li>demographics, range school,</li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">1.</span>model<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
               423.910155                298.522465                216.879433 
                  ps.grad   total.cte.courses.taken         ACTCompositeScore 
               163.427973                 85.063568                 78.556092 
                    MCA.M                     MCA.R             RaceEthnicity 
                54.838069                 47.045322                 44.689022 
          cte.achievement                     MCA.S              range.school 
                44.677379                 41.552785                 37.083829 
          economic.status                  took.ACT                    Gender 
                32.235480                 31.277917                 28.316536 
                 Dem_Desc           grad.year.covid           SpecialEdStatus 
                23.807517                 23.620718                 21.822964 
         pseo.participant                   ap.exam           english.learner 
                15.400838                 13.830043                  7.618909 </code></pre>
</div>
</div>
<p>Next, the accuracy of the model is computed and stored in a variable base_accuracy so we can compare it to our pruned trees later.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>base_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>base_accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8078219</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="pre-pruning" class="level3">
<h3 class="anchored" data-anchor-id="pre-pruning">Pre-pruning</h3>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grow a tree with minsplit of 40 and max depth of 10</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(grad.year<span class="fl">.1</span> <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> <span class="dv">5</span>, <span class="at">minsplit =</span> <span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/pre pruning plot meaningful emp NE grad year 1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.1 ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = 5, minsplit = 30))

Variables actually used in tree construction:
[1] Gender                  highest.cred.level      MCA.M                  
[4] ps.grad                 ps.grad.location        RaceEthnicity          
[7] range.school            total.cte.courses.taken

Root node error: 2901/15927 = 0.18214

n= 15927 

          CP nsplit rel error  xerror     xstd
1 0.02688728      0   1.00000 1.00000 0.016791
2 0.02206136      1   0.97311 1.00034 0.016793
3 0.00517063      2   0.95105 0.95105 0.016463
4 0.00310238      3   0.94588 0.94967 0.016454
5 0.00206825      4   0.94278 0.95691 0.016503
6 0.00160864      6   0.93864 0.95967 0.016522
7 0.00034471      9   0.93382 0.95209 0.016471
8 0.00000000     11   0.93313 0.95346 0.016480</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/pre pruning plot meaningful emp NE grad year 1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>accuracy_preprun</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.826571</code></pre>
</div>
</div>
<p>The pre-pruning resulted in a significantly less complex tree with a .827 accuracy. Let’s see what variables are important in this model.</p>
<p>The primary nodes are;</p>
<ol type="1">
<li>ps.grad.location
<ul>
<li>in-region</li>
</ul></li>
<li>highest.cred.level
<ul>
<li>Associate degree | Bachelor degree</li>
</ul></li>
<li>ps.grad
<ul>
<li>Attending ps</li>
</ul></li>
<li>range.school
<ul>
<li>range school</li>
</ul></li>
<li>RaceEthnicity
<ul>
<li>AI, Unknown, white</li>
</ul></li>
<li>total.cte.courses
<ul>
<li>the more the better</li>
</ul></li>
<li>Gender</li>
<li>MCA.M</li>
</ol>
<p>Overall, these are the most important themes;</p>
<ol type="1">
<li>post-secondary pathway is still very important</li>
<li>RaceEthnicity: a few demographic variables jump up in importance</li>
<li>range.school</li>
<li>CTE</li>
<li>preparations for post-secondary pathway are still important.</li>
<li>Missing:
<ul>
<li>ACTCompositeScore</li>
<li>MCA.S,</li>
<li>economic.status</li>
<li>took.ACT</li>
<li>pseo.participant,</li>
<li>ap.exam</li>
</ul></li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.preprune<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
              409.7165793               275.7306040               199.0706306 
                  ps.grad             RaceEthnicity              range.school 
              155.4334751                15.5892809                10.8011655 
  total.cte.courses.taken                     MCA.M           grad.year.covid 
                5.5101936                 3.8717886                 3.7912071 
                   Gender                     MCA.R                  took.ACT 
                3.7099009                 2.1972435                 1.8864513 
          SpecialEdStatus           cte.achievement           economic.status 
                1.5851381                 1.4814315                 1.3436322 
          english.learner                  Dem_Desc 
                1.1106198                 0.3484125 </code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="post-pruning" class="level3">
<h3 class="anchored" data-anchor-id="post-pruning">Post-pruning</h3>
<p>Next, let’s try postpruning. The idea here is to allow the decision tree to grow fully and observe the CP value. Next, we prune/cut the tree with the optimal CP value as the parameter as shown in below code:</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year.<span class="fl">1.</span>model<span class="sc">$</span>cptable</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.postprune <span class="ot">&lt;-</span> <span class="fu">prune</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model, <span class="at">cp =</span> cp_1se)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
rpart(formula = grad.year.1 ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))
  n= 15927 

           CP nsplit rel error    xerror       xstd
1 0.026887280      0 1.0000000 1.0000000 0.01679054
2 0.022061358      1 0.9731127 0.9986212 0.01678154
3 0.005170631      2 0.9510514 0.9510514 0.01646346

Variable importance
         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
                       40                        27                        20 
                  ps.grad 
                       13 

Node number 1: 15927 observations,    complexity param=0.02688728
  predicted class=No meaningful emp NE  expected loss=0.1821435  P(node) =1
    class counts:  2901 13026
   probabilities: 0.182 0.818 
  left son=2 (1374 obs) right son=3 (14553 obs)
  Primary splits:
      ps.grad.location          splits as  RLRLRR, improve=409.7166, (3590 missing)
      ps.grad.InstitutionSector splits as  RLRRLR, improve=324.4186, (3590 missing)
      highest.cred.level        splits as  LLLRR,  improve=279.3982, (3590 missing)
      ps.grad                   splits as  LRL,    improve=223.2052, (0 missing)
      SpecialEdStatus           splits as  LR,     improve= 44.3790, (0 missing)
  Surrogate splits:
      ps.grad.InstitutionSector splits as  RLRRLR, agree=0.964, adj=0.673, (0 split)
      highest.cred.level        splits as  LRLRR,  agree=0.939, adj=0.453, (0 split)
      ps.grad                   splits as  -RL,    agree=0.924, adj=0.315, (2951 split)

Node number 2: 1374 observations,    complexity param=0.02206136
  predicted class=Meaningful emp NE     expected loss=0.4716157  P(node) =0.0862686
    class counts:   726   648
   probabilities: 0.528 0.472 
  left son=4 (890 obs) right son=5 (484 obs)
  Primary splits:
      highest.cred.level        splits as  LLRR-,   improve=13.459770, (1 missing)
      took.ACT                  splits as  RL,      improve= 7.832194, (0 missing)
      MCA.M                     &lt; 1.5 to the right, improve= 5.724150, (30 missing)
      SpecialEdStatus           splits as  LR,      improve= 4.902956, (0 missing)
      ps.grad.InstitutionSector splits as  LL-LR-,  improve= 4.626896, (1 missing)
  Surrogate splits:
      SpecialEdStatus splits as  LR,      agree=0.689, adj=0.118, (1 split)
      took.ACT        splits as  RL,      agree=0.665, adj=0.050, (0 split)
      MCA.R           &lt; 2.5 to the right, agree=0.663, adj=0.043, (0 split)
      english.learner splits as  LR,      agree=0.661, adj=0.039, (0 split)
      grad.year.covid splits as  RL,      agree=0.658, adj=0.031, (0 split)

Node number 3: 14553 observations
  predicted class=No meaningful emp NE  expected loss=0.1494537  P(node) =0.9137314
    class counts:  2175 12378
   probabilities: 0.149 0.851 

Node number 4: 890 observations
  predicted class=Meaningful emp NE     expected loss=0.4202247  P(node) =0.05587995
    class counts:   516   374
   probabilities: 0.580 0.420 

Node number 5: 484 observations
  predicted class=No meaningful emp NE  expected loss=0.4338843  P(node) =0.03038865
    class counts:   210   274
   probabilities: 0.434 0.566 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.postprune, <span class="at">nn =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/postpruning meaningful emp NE grad year 1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.1 ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
[1] highest.cred.level ps.grad.location  

Root node error: 2901/15927 = 0.18214

n= 15927 

         CP nsplit rel error  xerror     xstd
1 0.0268873      0   1.00000 1.00000 0.016791
2 0.0220614      1   0.97311 0.99862 0.016782
3 0.0051706      2   0.95105 0.95105 0.016463</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/postpruning meaningful emp NE grad year 1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>accuracy_postprun</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8258386</code></pre>
</div>
</div>
<p><br></p>
<p>We now have a very simple tree, that might be a little too simple. Big piece, though, is that 91% of the individuals that did not graduate from college in the region did not have meaningful employment in Northeast.</p>
<p>It tells me the following;</p>
<ul>
<li>post-secondary pathways
<ul>
<li>ps.grad.location</li>
<li>ps.grad.InstitutionSector</li>
<li>highest.cred.level</li>
<li>ps.grad</li>
</ul></li>
<li>Demographics
<ul>
<li>SpecialEdStatus</li>
<li>english.learner</li>
<li>grad.year.covid</li>
</ul></li>
<li>post-secondary prep</li>
<li>Missing from base run
<ul>
<li>CTE stuff</li>
<li>Gender</li>
<li>RaceEthnicity</li>
<li></li>
</ul></li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.postprune<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
              409.7165793               275.7306040               199.0706306 
                  ps.grad           SpecialEdStatus                  took.ACT 
              129.2114194                 1.5851381                 0.6674266 
                    MCA.R           english.learner           grad.year.covid 
                0.5839983                 0.5283794                 0.4171416 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year.<span class="fl">1.</span>model.postprune<span class="sc">$</span>variable.importance</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> <span class="fu">sort</span>(importance, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(importance,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Variable Importance"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Variables"</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Importance"</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">las =</span> <span class="dv">2</span>,        <span class="co"># make axis labels vertical</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.names =</span> <span class="fl">0.8</span> <span class="co"># smaller font if needed</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/post pruning variable importance meaningful emp SW grad year 1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Now let’s compare the accuracy. The pre-pruned tree does get a bit better accuracy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(base_accuracy, accuracy_preprun, accuracy_postprun)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  base_accuracy accuracy_preprun accuracy_postprun
1     0.8078219         0.826571         0.8258386</code></pre>
</div>
</div>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<p>The variable importance across the models do not vary much. The most consistent variables that were high in the importance values were;</p>
<ul>
<li>Post-secondary pathway
<ul>
<li>ps.grad.location</li>
<li>ps.grad.InstitutionSector</li>
<li>highest.cred.level</li>
<li>ps.grad</li>
</ul></li>
<li>CTE engagement</li>
<li>range.school</li>
<li>RaceEthnicity</li>
<li>College prepwork
<ul>
<li>took.ACT</li>
<li>ACTCompositeScore</li>
<li>MCA.M</li>
<li>MCA.R</li>
</ul></li>
<li>Other demographics</li>
</ul>
<p><br></p>
</section>
</section>
<section id="five-years-after-graduation" class="level2">
<h2 class="anchored" data-anchor-id="five-years-after-graduation">Five years after graduation</h2>
<p>Next we will look at the variables importance at five years after graduation. At this point we will bring back the post-secondary variables.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="even">
<td style="text-align: left;">range.school</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">took.ACT</td>
</tr>
<tr class="even">
<td style="text-align: left;">ap.exam</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="even">
<td style="text-align: left;">english.learner</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="base-model-1" class="level3">
<h3 class="anchored" data-anchor-id="base-model-1">Base model</h3>
<p>First we will split the data into two sets, Train and Test, in a 70:30 ratio. The Train set is used for training and creating the model. The Test set is considered to be a dummy production environment to test predictions and evaluate the accuracy of the model.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(meaningful.emp.ne.grad.year<span class="fl">.5</span>), <span class="fu">nrow</span>(meaningful.emp.ne.grad.year<span class="fl">.5</span>) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year<span class="fl">.5</span>[sample_ind,]</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year<span class="fl">.5</span>[<span class="sc">-</span>sample_ind,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we create a decision tree model by calling the rpart function. Let’s first create a base model with default parameters and value. The CP (complexity parameter) is used to control tree growth. If the cost of adding a variable is higher then the value of CP, then tree growth stops.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/decision tree plot meaningful emp ne grad year 5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.5 ~ ., data = train, method = "class", 
    cp = 0)

Variables actually used in tree construction:
 [1] ACTCompositeScore         ap.exam                  
 [3] cte.achievement           Dem_Desc                 
 [5] economic.status           english.learner          
 [7] Gender                    highest.cred.level       
 [9] MCA.M                     MCA.R                    
[11] MCA.S                     ps.grad                  
[13] ps.grad.InstitutionSector ps.grad.location         
[15] pseo.participant          RaceEthnicity            
[17] range.school              SpecialEdStatus          
[19] took.ACT                  total.cte.courses.taken  

Root node error: 3866/19682 = 0.19642

n= 19682 

           CP nsplit rel error  xerror     xstd
1  1.3795e-03      0   1.00000 1.00000 0.014417
2  9.4844e-04     12   0.98189 1.00103 0.014423
3  8.1911e-04     18   0.97620 0.99974 0.014416
4  7.7600e-04     29   0.96560 1.00336 0.014436
5  6.4666e-04     34   0.96172 1.00569 0.014448
6  6.2080e-04     38   0.95913 1.00802 0.014461
7  5.1733e-04     44   0.95473 1.00517 0.014445
8  3.8800e-04     57   0.94801 1.00647 0.014452
9  3.6213e-04     74   0.94051 1.01190 0.014482
10 3.4489e-04     83   0.93663 1.01242 0.014484
11 3.2333e-04     86   0.93559 1.01681 0.014508
12 2.5867e-04     92   0.93326 1.01759 0.014512
13 2.1555e-04    149   0.91568 1.03544 0.014607
14 2.0693e-04    155   0.91438 1.03906 0.014626
15 1.7244e-04    171   0.90817 1.05613 0.014714
16 1.6167e-04    186   0.90533 1.06389 0.014754
17 1.5520e-04    205   0.90171 1.06544 0.014762
18 1.4781e-04    210   0.90093 1.06544 0.014762
19 1.4370e-04    223   0.89886 1.06544 0.014762
20 1.2933e-04    232   0.89757 1.07631 0.014817
21 1.1086e-04    270   0.89188 1.08303 0.014851
22 8.6222e-05    277   0.89110 1.09027 0.014887
23 7.9589e-05    322   0.88670 1.10605 0.014965
24 6.4666e-05    335   0.88567 1.11640 0.015015
25 5.1733e-05    351   0.88464 1.12054 0.015035
26 4.3111e-05    371   0.88360 1.13451 0.015102
27 3.6952e-05    389   0.88282 1.13761 0.015116
28 2.8741e-05    396   0.88257 1.13942 0.015125
29 0.0000e+00    409   0.88205 1.14123 0.015134</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/decision tree plot meaningful emp ne grad year 5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>The resulting model produced a VERY complex tree with too many nodes that it isn’t interpretable. However, examining the complexity parameters shows that I have an increasing cross-validated error which provides evidence of a decision tree with too much complexity.</p>
<p>Below are the values in variable important and there are a couple of themes;</p>
<ol type="1">
<li>Post-secondary pathway are significant</li>
<li>CTE engagement is significant</li>
<li>Post-secondary prep work is significant</li>
<li>range.school is important</li>
<li>Demographics are a bit lower</li>
<li>Difference from grad.year.1
<ol type="1">
<li>ps.grad isn’t as significant.</li>
</ol></li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">5.</span>model<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
                236.77079                 197.60819                 147.53906 
  total.cte.courses.taken         ACTCompositeScore                   ps.grad 
                130.38951                 126.64888                  88.55744 
          cte.achievement                     MCA.M                  Dem_Desc 
                 83.66798                  73.35285                  67.75636 
                    MCA.R                  took.ACT                     MCA.S 
                 63.40220                  51.51075                  45.37287 
             range.school           economic.status             RaceEthnicity 
                 44.61423                  40.82754                  38.64824 
                   Gender          pseo.participant           SpecialEdStatus 
                 38.64386                  37.73455                  28.72791 
                  ap.exam           english.learner 
                 26.11023                  17.50893 </code></pre>
</div>
</div>
<p>Next, the accuracy of the model is computed and stored in a variable base_accuracy so we can compare it to our pruned trees later.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>base_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.5</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>base_accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7777383</code></pre>
</div>
</div>
</section>
<section id="pre-pruning-1" class="level3">
<h3 class="anchored" data-anchor-id="pre-pruning-1">Pre-pruning</h3>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grow a tree with minsplit of 40 and max depth of 10</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(grad.year<span class="fl">.5</span> <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> <span class="dv">6</span>, <span class="at">minsplit =</span> <span class="dv">70</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/pre pruning plot meaningful emp ne grad year 5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.5 ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = 6, minsplit = 70))

Variables actually used in tree construction:
[1] cte.achievement         Dem_Desc                MCA.M                  
[4] ps.grad.location        range.school            SpecialEdStatus        
[7] total.cte.courses.taken

Root node error: 3866/19682 = 0.19642

n= 19682 

         CP nsplit rel error  xerror     xstd
1 0.0013795      0   1.00000 1.00000 0.014417
2 0.0000000      8   0.98862 0.99534 0.014392</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/pre pruning plot meaningful emp ne grad year 5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.5</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>accuracy_preprun</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8072546</code></pre>
</div>
</div>
<p>The pre-pruning resulted in a significantly less complex tree with a .807 accuracy. Let’s see what variables are important in this model.</p>
<p>The primary nodes are;</p>
<ol type="1">
<li>ps.grad.location
<ul>
<li>graduating from an institution outside of region has large impact on whether they have meaningful employment in region.</li>
</ul></li>
<li>range.school</li>
<li>Dem_Desc</li>
<li>cte engagement</li>
<li>SpecialEdStatus</li>
<li>MCA.M</li>
</ol>
<p>Primary variable themes are;</p>
<ul>
<li>Post-secondary pathway</li>
<li>range.school &amp; Dem_Desc</li>
<li>CTE engagement still important</li>
<li>a few demographics such as RaceEthnicity, english.learner, Gender and SpecialEdStatus</li>
<li>Missing from previous
<ul>
<li>economic.status</li>
<li>ap.exam</li>
<li>ACTCompositeScore</li>
<li>MCA.S</li>
<li>economic.status</li>
<li>pseo.participant</li>
<li>ap.exam</li>
</ul></li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.preprune<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
              208.0052050               128.7607645                84.1635218 
                  ps.grad                  Dem_Desc           cte.achievement 
               50.2950265                43.8778614                13.1703212 
             range.school           SpecialEdStatus   total.cte.courses.taken 
               11.1843358                 6.7409634                 6.3383468 
                    MCA.M                     MCA.R                  took.ACT 
                2.9194984                 1.8881561                 1.3965111 
                   Gender           english.learner             RaceEthnicity 
                0.6369425                 0.6270664                 0.1833186 </code></pre>
</div>
</div>
</section>
<section id="post-pruning-1" class="level3">
<h3 class="anchored" data-anchor-id="post-pruning-1">Post-pruning</h3>
<p>Next, let’s try postpruning. The idea here is to allow the decision tree to grow fully and observe the CP value. Next, we prune/cut the tree with the optimal CP value as the parameter as shown in below code:</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year.<span class="fl">5.</span>model<span class="sc">$</span>cptable</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.postprune <span class="ot">&lt;-</span> <span class="fu">prune</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model, <span class="at">cp =</span> .<span class="dv">00081911</span>)</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary</span></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
rpart(formula = grad.year.5 ~ ., data = train, method = "class", 
    cp = 0)
  n= 19682 

            CP nsplit rel error    xerror       xstd
1 0.0013795482      0 1.0000000 1.0000000 0.01441726
2 0.0009484394     12 0.9818934 1.0010347 0.01442289
3 0.0008191100     18 0.9762028 0.9997413 0.01441585

Variable importance
         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
                       35                        22                        15 
                  ps.grad                  Dem_Desc           cte.achievement 
                        8                         7                         2 
             range.school   total.cte.courses.taken           SpecialEdStatus 
                        2                         1                         1 
         pseo.participant                     MCA.S                     MCA.M 
                        1                         1                         1 
                    MCA.R                   ap.exam 
                        1                         1 

Node number 1: 19682 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.1964231  P(node) =1
    class counts:  3866 15816
   probabilities: 0.196 0.804 
  left son=2 (4541 obs) right son=3 (15141 obs)
  Primary splits:
      ps.grad.location          splits as  RLRLRR,   improve=208.00520, (5099 missing)
      ps.grad.InstitutionSector splits as  RLRRLR,   improve=139.93280, (5099 missing)
      highest.cred.level        splits as  LRLLR,    improve=103.46840, (5099 missing)
      ACTCompositeScore         &lt; 25.5 to the left,  improve= 41.38834, (8738 missing)
      ps.grad                   splits as  LRL,      improve= 38.69369, (0 missing)
  Surrogate splits:
      ps.grad.InstitutionSector splits as  RLRRLR, agree=0.881, adj=0.619, (0 split)
      highest.cred.level        splits as  LRLRR,  agree=0.813, adj=0.399, (0 split)
      ps.grad                   splits as  -RL,    agree=0.764, adj=0.242, (4932 split)

Node number 2: 4541 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.3201938  P(node) =0.2307184
    class counts:  1454  3087
   probabilities: 0.320 0.680 
  left son=4 (3321 obs) right son=5 (1220 obs)
  Primary splits:
      range.school      splits as  LR,       improve=11.184340, (0 missing)
      Dem_Desc          splits as  RRL,      improve=10.119550, (0 missing)
      ACTCompositeScore &lt; 22.5 to the left,  improve= 9.460576, (1375 missing)
      ps.grad.location  splits as  -L-R--,   improve= 6.290685, (0 missing)
      cte.achievement   splits as  LLR,      improve= 5.989616, (0 missing)

Node number 3: 15141 observations
  predicted class=No meaningful emp NE  expected loss=0.1593026  P(node) =0.7692816
    class counts:  2412 12729
   probabilities: 0.159 0.841 

Node number 4: 3321 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.3414634  P(node) =0.1687329
    class counts:  1134  2187
   probabilities: 0.341 0.659 
  left son=8 (2211 obs) right son=9 (1110 obs)
  Primary splits:
      Dem_Desc                splits as  RRL,      improve=31.581360, (0 missing)
      cte.achievement         splits as  LRR,      improve= 7.224739, (0 missing)
      ACTCompositeScore       &lt; 22.5 to the left,  improve= 5.725447, (917 missing)
      ps.grad.location        splits as  -L-R--,   improve= 5.103429, (0 missing)
      total.cte.courses.taken &lt; 2.5  to the right, improve= 4.934736, (0 missing)
  Surrogate splits:
      total.cte.courses.taken &lt; 9.5  to the left,  agree=0.668, adj=0.008, (0 split)
      RaceEthnicity           splits as  RLLLL,    agree=0.667, adj=0.004, (0 split)

Node number 5: 1220 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.2622951  P(node) =0.06198557
    class counts:   320   900
   probabilities: 0.262 0.738 
  left son=10 (92 obs) right son=11 (1128 obs)
  Primary splits:
      Dem_Desc           splits as  -LR,      improve=12.296500, (0 missing)
      pseo.participant   splits as  LR,       improve= 8.113080, (342 missing)
      ACTCompositeScore  &lt; 21.5 to the left,  improve= 4.758211, (458 missing)
      highest.cred.level splits as  RRLL-,    improve= 3.615573, (0 missing)
      cte.achievement    splits as  LLR,      improve= 2.505148, (0 missing)

Node number 8: 2211 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.3903211  P(node) =0.1123361
    class counts:   863  1348
   probabilities: 0.390 0.610 
  left son=16 (546 obs) right son=17 (1665 obs)
  Primary splits:
      cte.achievement           splits as  LRR,      improve=11.153340, (0 missing)
      ACTCompositeScore         &lt; 22.5 to the left,  improve= 6.924763, (556 missing)
      MCA.M                     &lt; 3.5  to the left,  improve= 5.953314, (30 missing)
      highest.cred.level        splits as  LRRL-,    improve= 5.885147, (0 missing)
      ps.grad.InstitutionSector splits as  RL-RL-,   improve= 4.104675, (0 missing)
  Surrogate splits:
      total.cte.courses.taken &lt; 3.5  to the right, agree=0.813, adj=0.244, (0 split)

Node number 9: 1110 observations
  predicted class=No meaningful emp NE  expected loss=0.2441441  P(node) =0.05639671
    class counts:   271   839
   probabilities: 0.244 0.756 

Node number 10: 92 observations,    complexity param=0.001379548
  predicted class=Meaningful emp NE     expected loss=0.4891304  P(node) =0.004674322
    class counts:    47    45
   probabilities: 0.511 0.489 
  left son=20 (30 obs) right son=21 (62 obs)
  Primary splits:
      total.cte.courses.taken &lt; 2.5  to the right, improve=3.184712, (0 missing)
      cte.achievement         splits as  LLR,      improve=3.120578, (0 missing)
      ACTCompositeScore       &lt; 24.5 to the left,  improve=3.083317, (31 missing)
      pseo.participant        splits as  LR,       improve=2.931881, (26 missing)
      MCA.M                   &lt; 2.5  to the left,  improve=1.335250, (0 missing)
  Surrogate splits:
      cte.achievement    splits as  LRR,      agree=0.880, adj=0.633, (0 split)
      highest.cred.level splits as  RRLR-,    agree=0.783, adj=0.333, (0 split)
      took.ACT           splits as  LR,       agree=0.750, adj=0.233, (0 split)
      Gender             splits as  RL,       agree=0.739, adj=0.200, (0 split)
      MCA.R              &lt; 2.5  to the left,  agree=0.739, adj=0.200, (0 split)

Node number 11: 1128 observations
  predicted class=No meaningful emp NE  expected loss=0.2420213  P(node) =0.05731125
    class counts:   273   855
   probabilities: 0.242 0.758 

Node number 16: 546 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.478022  P(node) =0.02774108
    class counts:   261   285
   probabilities: 0.478 0.522 
  left son=32 (503 obs) right son=33 (43 obs)
  Primary splits:
      SpecialEdStatus    splits as  LR,       improve=6.740963, (0 missing)
      ACTCompositeScore  &lt; 13.5 to the right, improve=3.312646, (193 missing)
      MCA.R              &lt; 2.5  to the right, improve=2.364393, (3 missing)
      MCA.S              &lt; 1.5  to the right, improve=2.278220, (212 missing)
      highest.cred.level splits as  LRRL-,    improve=2.049233, (0 missing)
  Surrogate splits:
      english.learner splits as  LR, agree=0.929, adj=0.093, (0 split)

Node number 17: 1665 observations
  predicted class=No meaningful emp NE  expected loss=0.3615616  P(node) =0.08459506
    class counts:   602  1063
   probabilities: 0.362 0.638 

Node number 20: 30 observations
  predicted class=Meaningful emp NE     expected loss=0.3  P(node) =0.001524235
    class counts:    21     9
   probabilities: 0.700 0.300 

Node number 21: 62 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.4193548  P(node) =0.003150086
    class counts:    26    36
   probabilities: 0.419 0.581 
  left son=42 (30 obs) right son=43 (32 obs)
  Primary splits:
      pseo.participant          splits as  LR,       improve=3.6737420, (13 missing)
      ACTCompositeScore         &lt; 24.5 to the left,  improve=2.2500000, (12 missing)
      ps.grad.InstitutionSector splits as  RL-LR-,   improve=0.9410231, (0 missing)
      cte.achievement           splits as  RLR,      improve=0.8002151, (0 missing)
      total.cte.courses.taken   &lt; 0.5  to the right, improve=0.6641366, (0 missing)
  Surrogate splits:
      MCA.M                   &lt; 2.5  to the left,  agree=0.633, adj=0.217, (13 split)
      took.ACT                splits as  LR,       agree=0.612, adj=0.174, (0 split)
      MCA.R                   &lt; 3.5  to the left,  agree=0.612, adj=0.174, (0 split)
      total.cte.courses.taken &lt; 0.5  to the right, agree=0.612, adj=0.174, (0 split)
      cte.achievement         splits as  RLR,      agree=0.592, adj=0.130, (0 split)

Node number 32: 503 observations,    complexity param=0.001379548
  predicted class=Meaningful emp NE     expected loss=0.499006  P(node) =0.02555635
    class counts:   252   251
   probabilities: 0.501 0.499 
  left son=64 (218 obs) right son=65 (285 obs)
  Primary splits:
      MCA.M                     &lt; 2.5  to the left,  improve=2.919498, (9 missing)
      MCA.S                     &lt; 1.5  to the right, improve=2.657934, (197 missing)
      ps.grad.InstitutionSector splits as  RL-RL-,   improve=1.992801, (0 missing)
      highest.cred.level        splits as  LRLL-,    improve=1.922138, (0 missing)
      ACTCompositeScore         &lt; 29.5 to the right, improve=1.517939, (161 missing)
  Surrogate splits:
      MCA.R                   &lt; 3.5  to the left,  agree=0.757, adj=0.429, (8 split)
      took.ACT                splits as  LR,       agree=0.670, adj=0.224, (1 split)
      total.cte.courses.taken &lt; 2.5  to the left,  agree=0.601, adj=0.062, (0 split)
      RaceEthnicity           splits as  RRLLR,    agree=0.585, adj=0.024, (0 split)
      highest.cred.level      splits as  RRLR-,    agree=0.583, adj=0.019, (0 split)

Node number 33: 43 observations
  predicted class=No meaningful emp NE  expected loss=0.2093023  P(node) =0.002184737
    class counts:     9    34
   probabilities: 0.209 0.791 

Node number 42: 30 observations
  predicted class=Meaningful emp NE     expected loss=0.4  P(node) =0.001524235
    class counts:    18    12
   probabilities: 0.600 0.400 

Node number 43: 32 observations
  predicted class=No meaningful emp NE  expected loss=0.25  P(node) =0.001625851
    class counts:     8    24
   probabilities: 0.250 0.750 

Node number 64: 218 observations,    complexity param=0.001379548
  predicted class=Meaningful emp NE     expected loss=0.4266055  P(node) =0.01107611
    class counts:   125    93
   probabilities: 0.573 0.427 
  left son=128 (162 obs) right son=129 (56 obs)
  Primary splits:
      MCA.S             &lt; 1.5  to the right, improve=3.684586, (142 missing)
      ACTCompositeScore &lt; 21.5 to the right, improve=2.916751, (107 missing)
      ps.grad.location  splits as  -L-R--,   improve=2.616594, (0 missing)
      MCA.R             &lt; 2.5  to the right, improve=2.029805, (2 missing)
      pseo.participant  splits as  RL,       improve=1.958430, (174 missing)
  Surrogate splits:
      MCA.R         &lt; 2.5  to the right, agree=0.803, adj=0.25, (140 split)
      RaceEthnicity splits as  R-RLL,    agree=0.776, adj=0.15, (1 split)

Node number 65: 285 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.445614  P(node) =0.01448024
    class counts:   127   158
   probabilities: 0.446 0.554 
  left son=130 (19 obs) right son=131 (266 obs)
  Primary splits:
      ACTCompositeScore         &lt; 27.5 to the right, improve=2.705916, (54 missing)
      ap.exam                   splits as  RL,       improve=2.561681, (0 missing)
      ps.grad.InstitutionSector splits as  RL-RL-,   improve=2.052715, (0 missing)
      total.cte.courses.taken   &lt; 7.5  to the right, improve=1.363819, (0 missing)
      highest.cred.level        splits as  RRLL-,    improve=1.169591, (0 missing)
  Surrogate splits:
      RaceEthnicity      splits as  RR-LR, agree=0.922, adj=0.053, (54 split)
      highest.cred.level splits as  RRRL-, agree=0.922, adj=0.053, (0 split)

Node number 128: 162 observations
  predicted class=Meaningful emp NE     expected loss=0.382716  P(node) =0.008230871
    class counts:   100    62
   probabilities: 0.617 0.383 

Node number 129: 56 observations,    complexity param=0.001379548
  predicted class=No meaningful emp NE  expected loss=0.4464286  P(node) =0.002845239
    class counts:    25    31
   probabilities: 0.446 0.554 
  left son=258 (23 obs) right son=259 (33 obs)
  Primary splits:
      highest.cred.level        splits as  LRR--,    improve=3.3043950, (0 missing)
      ps.grad.InstitutionSector splits as  -R-RL-,   improve=2.4114320, (0 missing)
      ACTCompositeScore         &lt; 15.5 to the right, improve=0.4000000, (36 missing)
      total.cte.courses.taken   &lt; 1.5  to the left,  improve=0.2500000, (0 missing)
      Gender                    splits as  RL,       improve=0.1947005, (0 missing)
  Surrogate splits:
      economic.status         splits as  RL,       agree=0.607, adj=0.043, (0 split)
      total.cte.courses.taken &lt; 3.5  to the left,  agree=0.607, adj=0.043, (0 split)

Node number 130: 19 observations
  predicted class=Meaningful emp NE     expected loss=0.3157895  P(node) =0.000965349
    class counts:    13     6
   probabilities: 0.684 0.316 

Node number 131: 266 observations,    complexity param=0.0009484394
  predicted class=No meaningful emp NE  expected loss=0.4285714  P(node) =0.01351489
    class counts:   114   152
   probabilities: 0.429 0.571 
  left son=262 (186 obs) right son=263 (80 obs)
  Primary splits:
      ps.grad.InstitutionSector splits as  RL-RL-,   improve=2.454531, (0 missing)
      highest.cred.level        splits as  LRLL-,    improve=1.315490, (0 missing)
      ap.exam                   splits as  RL,       improve=1.304945, (0 missing)
      total.cte.courses.taken   &lt; 7.5  to the right, improve=1.271080, (0 missing)
      ACTCompositeScore         &lt; 20.5 to the left,  improve=1.212519, (54 missing)
  Surrogate splits:
      highest.cred.level      splits as  LRLR-,    agree=0.846, adj=0.487, (0 split)
      total.cte.courses.taken &lt; 1.5  to the right, agree=0.711, adj=0.037, (0 split)

Node number 258: 23 observations
  predicted class=Meaningful emp NE     expected loss=0.3478261  P(node) =0.00116858
    class counts:    15     8
   probabilities: 0.652 0.348 

Node number 259: 33 observations
  predicted class=No meaningful emp NE  expected loss=0.3030303  P(node) =0.001676659
    class counts:    10    23
   probabilities: 0.303 0.697 

Node number 262: 186 observations,    complexity param=0.0009484394
  predicted class=No meaningful emp NE  expected loss=0.4731183  P(node) =0.009450259
    class counts:    88    98
   probabilities: 0.473 0.527 
  left son=524 (16 obs) right son=525 (170 obs)
  Primary splits:
      total.cte.courses.taken &lt; 7.5  to the right, improve=0.8076534, (0 missing)
      ACTCompositeScore       &lt; 20.5 to the left,  improve=0.6624972, (49 missing)
      pseo.participant        splits as  LR,       improve=0.5015480, (42 missing)
      highest.cred.level      splits as  RRL--,    improve=0.3207432, (0 missing)
      MCA.M                   &lt; 3.5  to the right, improve=0.2555232, (0 missing)

Node number 263: 80 observations,    complexity param=0.0009484394
  predicted class=No meaningful emp NE  expected loss=0.325  P(node) =0.004064628
    class counts:    26    54
   probabilities: 0.325 0.675 
  left son=526 (16 obs) right son=527 (64 obs)
  Primary splits:
      ap.exam                   splits as  RL,       improve=3.60000000, (0 missing)
      ACTCompositeScore         &lt; 22.5 to the left,  improve=0.85411760, (5 missing)
      total.cte.courses.taken   &lt; 2.5  to the left,  improve=0.57619050, (0 missing)
      economic.status           splits as  RL,       improve=0.12857140, (0 missing)
      ps.grad.InstitutionSector splits as  R--L--,   improve=0.09232737, (0 missing)
  Surrogate splits:
      RaceEthnicity      splits as  L---R, agree=0.812, adj=0.062, (0 split)
      highest.cred.level splits as  -RRL-, agree=0.812, adj=0.062, (0 split)

Node number 524: 16 observations
  predicted class=Meaningful emp NE     expected loss=0.375  P(node) =0.0008129255
    class counts:    10     6
   probabilities: 0.625 0.375 

Node number 525: 170 observations,    complexity param=0.0009484394
  predicted class=No meaningful emp NE  expected loss=0.4588235  P(node) =0.008637334
    class counts:    78    92
   probabilities: 0.459 0.541 
  left son=1050 (70 obs) right son=1051 (100 obs)
  Primary splits:
      MCA.S                   &lt; 2.5  to the left,  improve=0.8022222, (20 missing)
      total.cte.courses.taken &lt; 5.5  to the left,  improve=0.7420430, (0 missing)
      ACTCompositeScore       &lt; 16.5 to the left,  improve=0.5569680, (44 missing)
      Gender                  splits as  LR,       improve=0.4828678, (0 missing)
      highest.cred.level      splits as  RLL--,    improve=0.4723573, (0 missing)
  Surrogate splits:
      MCA.R              &lt; 3.5  to the left,  agree=0.720, adj=0.300, (20 split)
      highest.cred.level splits as  RRL--,    agree=0.647, adj=0.117, (0 split)
      MCA.M              &lt; 3.5  to the left,  agree=0.647, adj=0.117, (0 split)
      RaceEthnicity      splits as  RL--R,    agree=0.613, adj=0.033, (0 split)
      english.learner    splits as  RL,       agree=0.607, adj=0.017, (0 split)

Node number 526: 16 observations
  predicted class=Meaningful emp NE     expected loss=0.375  P(node) =0.0008129255
    class counts:    10     6
   probabilities: 0.625 0.375 

Node number 527: 64 observations
  predicted class=No meaningful emp NE  expected loss=0.25  P(node) =0.003251702
    class counts:    16    48
   probabilities: 0.250 0.750 

Node number 1050: 70 observations,    complexity param=0.0009484394
  predicted class=Meaningful emp NE     expected loss=0.4857143  P(node) =0.003556549
    class counts:    36    34
   probabilities: 0.514 0.486 
  left son=2100 (34 obs) right son=2101 (36 obs)
  Primary splits:
      pseo.participant        splits as  RL,       improve=1.3077910, (16 missing)
      MCA.M                   &lt; 3.5  to the right, improve=1.1840630, (0 missing)
      highest.cred.level      splits as  LLR--,    improve=1.0028600, (0 missing)
      ACTCompositeScore       &lt; 21.5 to the right, improve=0.9832105, (22 missing)
      total.cte.courses.taken &lt; 3.5  to the right, improve=0.6857143, (0 missing)
  Surrogate splits:
      Gender                  splits as  LR,       agree=0.685, adj=0.32, (16 split)
      took.ACT                splits as  RL,       agree=0.667, adj=0.28, (0 split)
      total.cte.courses.taken &lt; 5.5  to the left,  agree=0.593, adj=0.12, (0 split)
      MCA.S                   &lt; 1.5  to the right, agree=0.574, adj=0.08, (0 split)
      RaceEthnicity           splits as  RL--L,    agree=0.556, adj=0.04, (0 split)

Node number 1051: 100 observations,    complexity param=0.0009484394
  predicted class=No meaningful emp NE  expected loss=0.42  P(node) =0.005080784
    class counts:    42    58
   probabilities: 0.420 0.580 
  left son=2102 (20 obs) right son=2103 (80 obs)
  Primary splits:
      highest.cred.level      splits as  RRL--,    improve=2.6450000, (0 missing)
      pseo.participant        splits as  LR,       improve=2.3894330, (22 missing)
      ACTCompositeScore       &lt; 19.5 to the left,  improve=1.3675210, (22 missing)
      total.cte.courses.taken &lt; 5.5  to the left,  improve=0.8880217, (0 missing)
      took.ACT                splits as  LR,       improve=0.8878322, (0 missing)

Node number 2100: 34 observations
  predicted class=Meaningful emp NE     expected loss=0.3823529  P(node) =0.001727467
    class counts:    21    13
   probabilities: 0.618 0.382 

Node number 2101: 36 observations
  predicted class=No meaningful emp NE  expected loss=0.4166667  P(node) =0.001829082
    class counts:    15    21
   probabilities: 0.417 0.583 

Node number 2102: 20 observations
  predicted class=Meaningful emp NE     expected loss=0.35  P(node) =0.001016157
    class counts:    13     7
   probabilities: 0.650 0.350 

Node number 2103: 80 observations
  predicted class=No meaningful emp NE  expected loss=0.3625  P(node) =0.004064628
    class counts:    29    51
   probabilities: 0.363 0.638 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/postpruning meaningful emp ne grad year 5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.5 ~ ., data = train, method = "class", 
    cp = 0)

Variables actually used in tree construction:
 [1] ACTCompositeScore         ap.exam                  
 [3] cte.achievement           Dem_Desc                 
 [5] highest.cred.level        MCA.M                    
 [7] MCA.S                     ps.grad.InstitutionSector
 [9] ps.grad.location          pseo.participant         
[11] range.school              SpecialEdStatus          
[13] total.cte.courses.taken  

Root node error: 3866/19682 = 0.19642

n= 19682 

          CP nsplit rel error  xerror     xstd
1 0.00137955      0   1.00000 1.00000 0.014417
2 0.00094844     12   0.98189 1.00103 0.014423
3 0.00081911     18   0.97620 0.99974 0.014416</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/postpruning meaningful emp ne grad year 5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.5</span>)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>accuracy_postprun</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8057136</code></pre>
</div>
</div>
<p><br></p>
<p>We still end up with a highly complex tree that is difficult to interpret. Let’s check to see what variables are considered important.</p>
<ul>
<li>post-secondary pathway</li>
<li>range.school</li>
<li>Dem_Desc</li>
<li>CTE engagement</li>
<li>prep for post-secondary</li>
<li>Missing from this model
<ul>
<li>Gender</li>
</ul></li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.postprune<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
              208.0052050               131.2152959                91.7705100 
                  ps.grad                  Dem_Desc           cte.achievement 
               50.2950265                43.8778614                13.6495050 
             range.school   total.cte.courses.taken           SpecialEdStatus 
               11.1843358                 8.1775611                 6.7409634 
         pseo.participant                     MCA.S                     MCA.M 
                4.9815330                 4.5914319                 3.8117306 
                    MCA.R                   ap.exam         ACTCompositeScore 
                3.6888811                 3.6000000                 2.7059157 
                 took.ACT             RaceEthnicity                    Gender 
                2.4016042                 1.1824755                 1.0554355 
          english.learner           economic.status 
                0.6404367                 0.1436693 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year.<span class="fl">5.</span>model.postprune<span class="sc">$</span>variable.importance</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> <span class="fu">sort</span>(importance, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(importance,</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Variable Importance"</span>,</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Variables"</span>,</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Importance"</span>,</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">las =</span> <span class="dv">2</span>,        <span class="co"># make axis labels vertical</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.names =</span> <span class="fl">0.8</span>) <span class="co"># smaller font if needed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/post pruning variable importance grad year +5 county-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Now let’s compare the accuracy. The pre-pruned tree is the most accurate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(base_accuracy, accuracy_preprun, accuracy_postprun)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  base_accuracy accuracy_preprun accuracy_postprun
1     0.7777383        0.8072546         0.8057136</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="summary-1" class="level3">
<h3 class="anchored" data-anchor-id="summary-1">Summary</h3>
<p>Overall, the variables that were the most consistently important throughout the analysis were;</p>
<ul>
<li>Post-secondary pathways
<ul>
<li>ps.grad.location</li>
<li>ps.grad.InstitutionSector</li>
<li>highest.cred.level</li>
<li>ps.grad</li>
</ul></li>
<li>CTE egnagement</li>
<li>High School characteristics
<ul>
<li>Dem_Desc</li>
<li>range.school</li>
</ul></li>
<li>Post-secondary prep-work
<ul>
<li>ACTCompositeScore</li>
<li>MCA.M</li>
<li>MCA.R</li>
</ul></li>
<li>CTE engagement
<ul>
<li>total.cte.courses.taken</li>
<li>cte.achievement</li>
</ul></li>
<li>Demographics
<ul>
<li>Gender</li>
<li>Economic status</li>
<li>RaceEthnicty</li>
</ul></li>
</ul>
<p><br></p>
</section>
</section>
<section id="ten-years-after-graduation" class="level2">
<h2 class="anchored" data-anchor-id="ten-years-after-graduation">Ten years after graduation</h2>
<p>Next we will look at the variables importance at five years after graduation. At this point we will bring back the post-secondary variables.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="even">
<td style="text-align: left;">range.school</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">took.ACT</td>
</tr>
<tr class="even">
<td style="text-align: left;">ap.exam</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="even">
<td style="text-align: left;">english.learner</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<section id="base-model-2" class="level3">
<h3 class="anchored" data-anchor-id="base-model-2">Base model</h3>
<p>First we will split the data into two sets, Train and Test, in a 70:30 ratio. The Train set is used for training and creating the model. The Test set is considered to be a dummy production environment to test predictions and evaluate the accuracy of the model.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(meaningful.emp.ne.grad.year<span class="fl">.10</span>), <span class="fu">nrow</span>(meaningful.emp.ne.grad.year<span class="fl">.10</span>) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year<span class="fl">.10</span>[sample_ind,]</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year<span class="fl">.10</span>[<span class="sc">-</span>sample_ind,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we create a decision tree model by calling the rpart function. Let’s first create a base model with default parameters and value. The CP (complexity parameter) is used to control tree growth. If the cost of adding a variable is higher then the value of CP, then tree growth stops.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/decision tree plot meaningful emp ne grad year 10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.10 ~ ., data = train, method = "class", 
    cp = 0)

Variables actually used in tree construction:
 [1] ACTCompositeScore         ap.exam                  
 [3] cte.achievement           Dem_Desc                 
 [5] economic.status           english.learner          
 [7] Gender                    highest.cred.level       
 [9] MCA.M                     MCA.R                    
[11] MCA.S                     ps.grad                  
[13] ps.grad.InstitutionSector ps.grad.location         
[15] pseo.participant          RaceEthnicity            
[17] range.school              SpecialEdStatus          
[19] took.ACT                  total.cte.courses.taken  

Root node error: 2414/13817 = 0.17471

n= 13817 

           CP nsplit rel error xerror     xstd
1  9.6658e-04      0   1.00000 1.0000 0.018490
2  7.7327e-04      3   0.99710 1.0153 0.018601
3  6.9042e-04     38   0.96272 1.0195 0.018630
4  6.2138e-04     41   0.96065 1.0215 0.018645
5  5.5233e-04     49   0.95568 1.0228 0.018654
6  4.1425e-04     52   0.95402 1.0249 0.018669
7  3.7659e-04     56   0.95236 1.0385 0.018766
8  3.1069e-04     72   0.94490 1.0510 0.018853
9  2.9589e-04     76   0.94366 1.0592 0.018910
10 2.7617e-04     83   0.94159 1.0626 0.018933
11 2.4855e-04     89   0.93993 1.0688 0.018975
12 2.0713e-04     97   0.93745 1.0804 0.019054
13 1.7754e-04    109   0.93496 1.0882 0.019107
14 1.6570e-04    131   0.92833 1.0949 0.019152
15 1.3808e-04    146   0.92585 1.1102 0.019253
16 1.1836e-04    184   0.92046 1.1160 0.019291
17 1.0356e-04    205   0.91674 1.1210 0.019324
18 8.2850e-05    213   0.91591 1.1247 0.019348
19 6.9042e-05    239   0.91342 1.1363 0.019423
20 5.9179e-05    257   0.91218 1.1421 0.019460
21 4.6028e-05    264   0.91176 1.1433 0.019468
22 4.1425e-05    273   0.91135 1.1433 0.019468
23 0.0000e+00    283   0.91094 1.1454 0.019482</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/decision tree plot meaningful emp ne grad year 10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>The resulting model produced a VERY complex tree with too many nodes that it isn’t interpretable. However, examining the complexity parameters shows that I have an increasing cross-validated error which provides evidence of a decision tree with too much complexity.</p>
<p>Below are the values in variable important and it shows the following themes are important;</p>
<ul>
<li>Post-secondary pathway
<ul>
<li>ps.grad drops, though</li>
</ul></li>
<li>CTE engagement</li>
<li>Post-secondary prep work</li>
<li>HS Characteristics - range.school &amp; Dem_Desc</li>
<li>Demographics
<ul>
<li>Gender</li>
<li>RaceEthnicity</li>
<li>SpecialEdStatus</li>
</ul></li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">10.</span>model<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector   total.cte.courses.taken 
                95.127046                 90.998019                 89.652071 
       highest.cred.level         ACTCompositeScore                     MCA.M 
                77.364796                 76.759481                 62.137435 
                    MCA.R           cte.achievement              range.school 
                47.648540                 45.355126                 40.364727 
                 took.ACT                  Dem_Desc                    Gender 
                29.542077                 29.187427                 24.452716 
                    MCA.S           SpecialEdStatus           economic.status 
                23.178822                 23.166348                 19.644456 
            RaceEthnicity                   ps.grad          pseo.participant 
                18.047604                 17.194412                 14.202348 
          english.learner                   ap.exam 
                 8.666995                  6.346525 </code></pre>
</div>
</div>
<p>Next, the accuracy of the model is computed and stored in a variable base_accuracy so we can compare it to our pruned trees later.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>base_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.10</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>base_accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8081729</code></pre>
</div>
</div>
</section>
<section id="pre-pruning-2" class="level3">
<h3 class="anchored" data-anchor-id="pre-pruning-2">Pre-pruning</h3>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grow a tree with minsplit of 40 and max depth of 10</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(grad.year<span class="fl">.10</span> <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> <span class="dv">6</span>, <span class="at">minsplit =</span> <span class="dv">40</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/pre pruning plot meaningful emp ne grad year 10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.10 ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = 6, minsplit = 40))

Variables actually used in tree construction:
[1] ACTCompositeScore       Dem_Desc                MCA.M                  
[4] ps.grad                 ps.grad.location        pseo.participant       
[7] range.school            total.cte.courses.taken

Root node error: 2414/13817 = 0.17471

n= 13817 

          CP nsplit rel error xerror     xstd
1 0.00096658      0   1.00000 1.0000 0.018490
2 0.00055233      3   0.99710 1.0029 0.018511
3 0.00020713      6   0.99544 1.0108 0.018568
4 0.00008285      8   0.99503 1.0099 0.018562
5 0.00000000     13   0.99461 1.0099 0.018562</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/pre pruning plot meaningful emp ne grad year 10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.10</span>)</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>accuracy_preprun</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8341776</code></pre>
</div>
</div>
<p><br></p>
<p>The pre-pruning resulted in a significantly less complex tree with a .834 accuracy. Let’s see what variables are important in this model.</p>
<p>The primary nodes are;</p>
<ul>
<li>ps.grad.location</li>
<li>Dem_Desc</li>
<li>total.cte.courses.taken</li>
<li>range.school</li>
<li>MCA.M</li>
<li>pseo.participant</li>
</ul>
<p>This model does indicate a difference in importance when pruned.</p>
<ul>
<li>Post-secondary pathway</li>
<li>CTE engagement - the only one that leads to any sort of meaningful emp in NE</li>
<li>High school characteristics</li>
<li>Post-secondary prep</li>
<li>Demographics</li>
<li>Missing include
<ul>
<li>ACTCompositeScore</li>
<li>economic.status</li>
</ul></li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.preprune<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
              74.82899079               36.54707755               30.86998873 
                 Dem_Desc   total.cte.courses.taken              range.school 
              27.33187509               20.90931444               12.13670524 
          cte.achievement                     MCA.M          pseo.participant 
               3.22639779                2.15252417                1.96491228 
                  ps.grad         ACTCompositeScore                     MCA.R 
               1.53846154                1.32581454                1.06140351 
                 took.ACT                     MCA.S             RaceEthnicity 
               0.64473684                0.42105263                0.30334406 
          SpecialEdStatus           english.learner                    Gender 
               0.28662463                0.12216788                0.09029982 
                  ap.exam 
               0.08333333 </code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="post-pruning-2" class="level3">
<h3 class="anchored" data-anchor-id="post-pruning-2">Post-pruning</h3>
<p>Next, let’s try postpruning. The idea here is to allow the decision tree to grow fully and observe the CP value. Next, we prune/cut the tree with the optimal CP value as the parameter as shown in below code:</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year.<span class="fl">10.</span>model<span class="sc">$</span>cptable</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.postprune <span class="ot">&lt;-</span> <span class="fu">prune</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model, <span class="at">cp =</span> <span class="fl">8.1911e-04</span>)</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary</span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
rpart(formula = grad.year.10 ~ ., data = train, method = "class", 
    cp = 0)
  n= 13817 

            CP nsplit rel error   xerror       xstd
1 0.0009665838      0 1.0000000 1.000000 0.01848988
2 0.0008191100      3 0.9971002 1.015327 0.01860079

Variable importance
         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
                       45                        22                        18 
                 Dem_Desc   total.cte.courses.taken 
                        8                         7 

Node number 1: 13817 observations,    complexity param=0.0009665838
  predicted class=No meaningful emp NE  expected loss=0.1747123  P(node) =1
    class counts:  2414 11403
   probabilities: 0.175 0.825 
  left son=2 (3161 obs) right son=3 (10656 obs)
  Primary splits:
      ps.grad.location          splits as  RLRRRR,   improve=74.82899, (3523 missing)
      ps.grad.InstitutionSector splits as  RLRRLR,   improve=47.47255, (3523 missing)
      highest.cred.level        splits as  LRLRR,    improve=36.52843, (3523 missing)
      Dem_Desc                  splits as  RRL,      improve=29.91859, (0 missing)
      ACTCompositeScore         &lt; 25.5 to the left,  improve=16.40332, (6508 missing)
  Surrogate splits:
      ps.grad.InstitutionSector splits as  RRRRLR, agree=0.842, adj=0.485, (0 split)
      highest.cred.level        splits as  LRLRR,  agree=0.819, adj=0.410, (0 split)

Node number 2: 3161 observations,    complexity param=0.0009665838
  predicted class=No meaningful emp NE  expected loss=0.2654223  P(node) =0.2287761
    class counts:   839  2322
   probabilities: 0.265 0.735 
  left son=4 (2399 obs) right son=5 (762 obs)
  Primary splits:
      Dem_Desc                  splits as  RRL,      improve=13.402120, (0 missing)
      ACTCompositeScore         &lt; 22.5 to the left,  improve= 4.701445, (1165 missing)
      ps.grad.InstitutionSector splits as  RL-LL-,   improve= 4.688029, (0 missing)
      total.cte.courses.taken   &lt; 6.5  to the right, improve= 2.935598, (0 missing)
      economic.status           splits as  LR,       improve= 2.838957, (0 missing)
  Surrogate splits:
      total.cte.courses.taken &lt; 13.5 to the left,  agree=0.759, adj=0.001, (0 split)

Node number 3: 10656 observations
  predicted class=No meaningful emp NE  expected loss=0.1478041  P(node) =0.7712239
    class counts:  1575  9081
   probabilities: 0.148 0.852 

Node number 4: 2399 observations
  predicted class=No meaningful emp NE  expected loss=0.2913714  P(node) =0.1736267
    class counts:   699  1700
   probabilities: 0.291 0.709 

Node number 5: 762 observations,    complexity param=0.0009665838
  predicted class=No meaningful emp NE  expected loss=0.183727  P(node) =0.05514945
    class counts:   140   622
   probabilities: 0.184 0.816 
  left son=10 (29 obs) right son=11 (733 obs)
  Primary splits:
      total.cte.courses.taken   &lt; 6.5  to the right, improve=11.512440, (0 missing)
      range.school              splits as  RL,       improve= 5.832547, (0 missing)
      ps.grad.InstitutionSector splits as  RL-LL-,   improve= 2.867758, (0 missing)
      highest.cred.level        splits as  LRLL-,    improve= 2.484231, (0 missing)
      MCA.R                     &lt; 1.5  to the left,  improve= 1.498508, (13 missing)

Node number 10: 29 observations
  predicted class=Meaningful emp NE     expected loss=0.3793103  P(node) =0.002098864
    class counts:    18    11
   probabilities: 0.621 0.379 

Node number 11: 733 observations
  predicted class=No meaningful emp NE  expected loss=0.1664393  P(node) =0.05305059
    class counts:   122   611
   probabilities: 0.166 0.834 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/postpruning meaningful emp ne grad year 10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.10 ~ ., data = train, method = "class", 
    cp = 0)

Variables actually used in tree construction:
[1] Dem_Desc                ps.grad.location        total.cte.courses.taken

Root node error: 2414/13817 = 0.17471

n= 13817 

          CP nsplit rel error xerror     xstd
1 0.00096658      0    1.0000 1.0000 0.018490
2 0.00081911      3    0.9971 1.0153 0.018601</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/postpruning meaningful emp ne grad year 10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.10</span>)</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>accuracy_postprun</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8341776</code></pre>
</div>
</div>
<p><br></p>
<p>The accuracy is still a bit lower than pre-pruning - .8341776</p>
<p>We end up with a very simply tree. Let’s check to see what variables are considered important.</p>
<ul>
<li>Post-secondary pathway</li>
<li>Dem_Desc</li>
<li>CTE engagement</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.postprune<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         ps.grad.location ps.grad.InstitutionSector        highest.cred.level 
                 74.82899                  36.26638                  30.70332 
                 Dem_Desc   total.cte.courses.taken 
                 13.40212                  11.53003 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> meaningful.emp.ne.grad.year.<span class="fl">10.</span>model.postprune<span class="sc">$</span>variable.importance</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> <span class="fu">sort</span>(importance, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(importance,</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Variable Importance"</span>,</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Variables"</span>,</span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Importance"</span>,</span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">las =</span> <span class="dv">2</span>,        <span class="co"># make axis labels vertical</span></span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.names =</span> <span class="fl">0.8</span>) <span class="co"># smaller font if needed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/post pruning variable importance meaningful emp ne grad year 10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Now let’s compare the accuracy. The prepruned tree/model looks to be the best.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(base_accuracy, accuracy_preprun, accuracy_postprun)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  base_accuracy accuracy_preprun accuracy_postprun
1     0.8081729        0.8341776         0.8341776</code></pre>
</div>
</div>
</section>
<section id="summary-2" class="level3">
<h3 class="anchored" data-anchor-id="summary-2">Summary</h3>
<p>Overall, the variables that were the most consistently important throughout the analysis were the following;</p>
<ul>
<li>The post-secondary pathway</li>
<li>CTE engagement</li>
<li>High school characteristics - Dem_Desc &amp; Range School</li>
<li>Post-secondary prep work</li>
<li>A few demographics
<ul>
<li>Gender</li>
<li>SpecialEdStatus</li>
<li>RaceEthnicity</li>
</ul></li>
</ul>
<p><br></p>
</section>
</section>
<section id="summary-across-time" class="level2">
<h2 class="anchored" data-anchor-id="summary-across-time">Summary across time</h2>
<ul>
<li>1 year after graduation
<ul>
<li>Post-secondary pathways
<ul>
<li>ps.grad.location</li>
<li>ps.grad.InstitutionSector</li>
<li>highest.cred.level</li>
<li>ps.grad</li>
</ul></li>
<li>HS Characteristics
<ul>
<li>Dem_Desc</li>
<li>range.school</li>
</ul></li>
<li>RaceEthnicity</li>
<li>CTE engagement</li>
<li>Gender</li>
<li>College Prepwork
<ul>
<li>MCA.M</li>
</ul></li>
</ul></li>
<li>5 years after graduation
<ul>
<li>Post-secondary pathways
<ul>
<li>ps.grad.location</li>
<li>highest.cred.level</li>
</ul></li>
<li>HS characteristics
<ul>
<li>Dem_Desc</li>
<li>Range school</li>
</ul></li>
<li>College prepwork
<ul>
<li>ACTCompositeScore</li>
<li>pseo.participant</li>
<li>MCA.M</li>
<li>MCA.S</li>
</ul></li>
<li>CTE engagement</li>
<li>Gender</li>
</ul></li>
<li>10 years after graduation
<ul>
<li>Post-secondary pathway
<ul>
<li>ps.grad.location</li>
</ul></li>
<li>Dem_Desc</li>
<li>CTE engagement</li>
<li>Post-secondary prepwork</li>
</ul></li>
</ul>
<p>So what doesn’t come up as much?</p>
<ul>
<li><p>Demographic variables</p>
<ul>
<li>Gender</li>
<li>grad.year.covid</li>
<li>economic.status</li>
<li>SpecialEdStatus</li>
<li>english.learner</li>
</ul></li>
<li><p>High school accomplishment</p>
<ul>
<li>pseo.participant</li>
</ul></li>
<li><p>Post-secondary prep</p>
<ul>
<li><p>took.ACT</p></li>
<li><p>MCA.S</p></li>
<li><p>ap.exam</p></li>
</ul></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>